// Inhalt der Club-App-Anleitung (Texte). Bilder: bild/<name>.png (ganze Seite) und bild/s-<name>.png (Ausschnitt).
export const VERSION = { anleitung: 8, app: "2.95.0", stand: "08.10.2026" };
export const INHALT = [
  ["So fängst du an", "in 5 Schritten"], ["1. Startseite", "einfache Ansicht – das Wichtigste auf einen Blick"], ["2. Erweiterte Ansicht", "alle Funktionen, Anzeigen im Kopf"],
  ["3. Nachrichten", "Chats, Schreiben, Diktieren, wichtige Nachrichten, Chats archivieren"], ["4. Termine", "zu- und absagen, Mitfahren, Kalender, Terminanfragen mit Erinnerung"], ["5. Mitglieder", "wer ist online, Status, Kontakt, Anklopfen"],
  ["6. Pinnwand", "kurze Zettel für alle oder einzelne"], ["7. SOS – Notfall", "Notrufnummern, Notfallpass, Kontakte, SOS an alle"], ["8. Einstellungen", "Sprachansagen, Farbschemen, Benachrichtigungen, Privatsphäre"],
  ["9. Notbetrieb", "wenn der Server einmal ausfällt"], ["10. Fotos & Alben", "eigene Alben mit Namen"], ["11. Archiv & Chronik", "dein Ordner, die Clubchronik zum Blättern"],
  ["12. Helfen & Leihen", "Hilfe suchen, helfen, „nach Absprache“"], ["13. Bedienen, Anmelden & ohne Netz", "Zurück-Taste, Rückfragen, neues Gerät, kein Internet"],
  ["14. Spiele", "Tic-Tac-Toe, Schach, Bauernskat, Küchenterror – gegen Computer oder Mitglieder"], ["15. Hilfe & Tipps", "das „?“, Hilfe-Zentrum, „Kurz erklärt“"],
  ["16. Dienstwünsche", "mit Twinkey eintragen, leerer Wunschbogen zum Ausdrucken"], ["17. Meine Daten haben sich geändert", "neue Anschrift, Handynummer & Co. melden"],
  ["18. Neu in Version 6", "Mein Bild, Anwesenheitstafel, Anrufen von der Kachel, mehr am Pfeil, Mein Dienst, Meine Daten und mehr"],
  ["19. Neu in Version 7", "Meldung beim Öffnen, weniger Fenster, Gruppen-Admins, Bauernskat nach Köcheclub-Regeln und mehr"],
  ["20. Neu in Version 8", "Schritt-für-Schritt-Hilfe, Sprachsteuerung, 👆 Was kann ich antippen?, neue Spiele, Inhaltsverzeichnis und mehr"],
];
export const GUT_ZU_WISSEN = [
  "<b>Gut zu wissen:</b> Alle Bilder zeigen <b>Beispieldaten</b> – Namen wie „Max Mustermann“ und alle Telefonnummern sind erfunden. In deiner App stehen die echten Mitglieder und Termine.",
  "Die App hat eine <b>einfache</b> und eine <b>erweiterte Ansicht</b> – Umschalten geht jederzeit (Teil 1 und 2).",
  "Die Farben kannst du in den Einstellungen ändern („Lieblingsfarbe“) – es gibt jetzt <b>22 Farbschemen</b>. Die Bilder zeigen „Köcheclub Klassik“ am Tag.",
  "<b>Neu in Version 8</b> – alles in <b>Teil 20</b>: 🤝 wie viel Hilfe du möchtest, 👣 Schritt für Schritt mit rotem Rahmen, 🎙️ Sprachsteuerung („Nachricht an Klaus“), 👆 Was kann ich antippen?, 🎲 Mensch ärgere dich nicht, 🧑‍🍳 Fang den Koch, 👑 Doppelkopf, 🗂️ Inhaltsverzeichnis deiner Ordner und mehr. Was in Version 7 dazukam, steht in <b>Teil 19</b>.",
  "<b><u>Beachte:</u></b> Die Club-App ist noch eine Beta-Version. Einige Funktionen können sich mit der Zeit noch ändern, weil ständig weiterentwickelt wird.",
];
export const START_SCHRITTE = [
  ["s-ohne-link", "Persönlichen Link öffnen", "Von Hansi bekommst du einen <b>persönlichen Link</b> (per WhatsApp oder Mail) – oder eine <b>Einrichtungskarte</b> mit QR-Code: Kamera draufhalten und den Link antippen. Einfach antippen – die App öffnet sich und weiß, wer du bist. Den Link nicht weitergeben: Er ist dein Schlüssel."],
  ["@icon", "Auf den Startbildschirm legen", "Die App zeigt dir mit <b>„📲 Köcheclub als App einrichten“</b> Schritt für Schritt, was du tippen musst – passend zu deinem Handy. Kurz: <b>iPhone (Safari):</b> Teilen ⬆️ → „Zum Home-Bildschirm“. <b>Android (Chrome):</b> ⋮ → „App installieren“. Danach die App immer über das Köcheclub-Symbol öffnen."],
  ["s-kurzcode", "Mit Code anmelden", "Fragt die neue App nach einem Code: im Browser zeigt die App bei der Einrichtung einen <b>6-stelligen Code</b> – den hier eintippen, dann dreht sich kurz die Kochmütze und die App startet. <b>iPhone/iPad:</b> erst die Kochmütze auf den Home-Bildschirm legen und den Code <b>dort</b> eingeben – dann reicht ein einziger Code. Auch für ein zweites Gerät: ⚙️ → App-Installation → „🔢 Code für ein anderes Gerät“."],
  ["s-benachr-ein", "Benachrichtigungen einschalten", "Damit Nachrichten und Termine aufs Handy kommen: unter <b>Heute wichtig</b> auf <b>Einschalten</b> tippen und erlauben."],
  ["s-status", "Status setzen", "Oben im Kopf zeigst du den anderen, ob du <b>verfügbar</b>, beschäftigt, im Urlaub, krank oder abwesend bist. Antippen und auswählen."],
];
export const TEILE = [
  { titel: "1. Startseite", unter: "Einfache Ansicht – das Wichtigste auf einen Blick", bild: "start-einfach",
    legende: [["Status", "dein Status – antippen zum Ändern"], ["Termin-Karte", "der nächste Termin mit deiner Antwort"], ["Neue Nachrichten", "Zahl der ungelesenen Nachrichten"], ["Mitglieder", "wie viele es sind und wer gerade online ist"], ["Nächster Termin", "in wie vielen Tagen"],
      ["Ansicht", "einfach oder erweitert"], ["Version", "Stand der App, Update prüfen"], ["Schnellzugriff", "die großen Kacheln"], ["Lupe", "alles in der App suchen"], ["Fußleiste", "immer unten: Start, Termine, Nachrichten, Mitglieder, Mehr"]],
    abschnitte: [
      { nr: 1, titel: "Status", zeilen: [["s-status", "Mein Status", "Zeigt den anderen, wie du gerade erreichbar bist: 🟢 verfügbar, 🟠 beschäftigt, 🏖️ Urlaub, 🤒 krank, ⚪ abwesend – auf Wunsch mit „bis“-Datum. Hast du eine Ruhezeit eingestellt, steht dort automatisch „🌙 Ruhezeit bis 07:00“."]] },
      { nr: 2, titel: "Termin-Karte und die drei Felder", zeilen: [
        ["s-termin-karte", "Termin-Karte", "Der nächste Termin mit Datum, Uhrzeit und Ort – und deine Antwort (z. B. ✅ Ich komme) mit der Zahl der Zusagen. Antippen öffnet den Termin."],
        ["s-mini0", "Neue Nachrichten", "Die Zahl der ungelesenen Nachrichten. Gibt es Neues, läuft ein <b>orangefarbener Rand</b> („Ameisenstraße“) um das Feld. Antippen öffnet die Nachrichten."],
        ["s-mini1", "Mitglieder", "Wie viele Mitglieder es gibt – daneben der <b>grüne Punkt mit der Zahl</b>, wer gerade online ist (grau = gerade niemand). <b>Antippen</b> öffnet direkt die Mitglieder-Seite <b>nur mit denen, die gerade online sind</b>."],
        ["s-mini2", "Nächster Termin", "In wie vielen Tagen der nächste Termin ist. Ab 5 Tagen vorher läuft ein hellgrüner Rand, ab 3 Tagen ein orangefarbener, am Vortag und am Tag selbst ein roter."]] },
      { nr: 6, titel: "Ansicht, Version und Schnellzugriff", zeilen: [
        ["s-ansicht", "Einfache Ansicht", "Antippen schaltet zur <b>erweiterten Ansicht</b> mit allen Funktionen (Teil 2). Zurück geht es genauso."],
        ["s-version", "Version", "Zeigt die App-Version. Antippen prüft, ob es ein Update gibt. Updates kommen sonst von selbst – ein Hinweis fragt dann kurz nach."],
        ["s-kachel0", "Termine", "Alle Termine, zu- und absagen (Teil 4)."], ["s-kachel1", "Nachrichten", "Chats mit einzelnen Mitgliedern und Gruppen (Teil 3). Die Zahl zeigt Ungelesenes."],
        ["s-kachel2", "Pinnwand", "Kurze Zettel für alle oder einzelne (Teil 6). Die Zahl zeigt neue Zettel."], ["s-kachel3", "Mein Dienst", "Deine Dienste aus dem Dienstplan."],
        ["s-kachel4", "Mitglieder", "Alle Mitglieder mit Status, Amt und Kontakt (Teil 5)."], ["s-kachel5", "Meine Dokumente", "Anleitungen und Unterlagen – öffnen sich direkt in der App mit „‹ Zurück zur App“, Drucken und Teilen. Auch diese Anleitung."],
        ["s-kachel6", "SOS – Notfall", "Notrufnummern und Kontakte im Notfall (Teil 7)."],
        ["s-heute-wichtig", "Heute wichtig", "Was heute für dich ansteht: neue Nachrichten, offene Abstimmungen, Hinweise. Antippen führt direkt hin."],
        ["s-mehr-funktionen", "Mehr Funktionen anzeigen", "Schaltet zur erweiterten Ansicht."], ["s-app-schliessen", "App schließen", "Beendet die App sauber."]] },
      { nr: 9, titel: "Lupe und Fußleiste", zeilen: [
        ["s-lupe", "Lupe", "Sucht in Nachrichten, Terminen, Pinnwand, Archiv und mehr – schon ab 2 Buchstaben."],
        ["s-fuss", "Fußleiste", "Immer unten zu sehen: <b>Start</b>, <b>Termine</b>, <b>Nachrichten</b>, <b>Mitglieder</b> und <b>Mehr</b> (Einstellungen). Die roten Zahlen zeigen Neues, die grüne Zahl, wer online ist."]] },
    ] },
  { titel: "2. Erweiterte Ansicht", unter: "Alle Funktionen und die Anzeigen im Kopf", bild: "start-erweitert",
    legende: [["Lämpchen", "Verbindung – grün ist alles gut"], ["Tag/Nacht", "hell oder dunkel"], ["Aktualisieren", "neu laden"], ["Blättern", "nächste Karte"], ["Springen", "zur letzten Karte"], ["Punkte", "welche Karte gerade gezeigt wird"], ["Register", "Club, Meins, Technik"], ["Kacheln", "alle Funktionen"]],
    abschnitte: [
      { nr: 1, titel: "Anzeigen und Knöpfe im Kopf", zeilen: [
        ["s-leds", "Lämpchen", "Grün = <b>Verbindung in Ordnung</b> · Rot = keine Verbindung · Blau = Wartung · Grau = wird geprüft. Antippen zeigt kurz „✅ Verbindung in Ordnung“ oder „⚠️ Störung“ – mit <b>Test-Mitteilung an mich</b> und <b>Problem melden</b>. Der Punkt daneben zeigt, wer online ist."],
        ["s-modus", "Tag/Nacht", "Schaltet zwischen hell und dunkel. Das „T“ heißt Tag, das „N“ Nacht, „A“ automatisch."],
        ["s-aktualisieren", "Aktualisieren", "Lädt alles neu vom Server."]] },
      { nr: 4, titel: "Karten im Kopf und Register", zeilen: [
        ["s-pfeile", "Blättern", "Mit ‹ › blätterst du durch die Karten im Kopf: nächster Termin, Wetter, Schnellstart und mehr. « » springen zur ersten oder letzten Karte. Wischen geht auch."],
        ["s-punkte", "Punkte", "Zeigen, welche Karte gerade zu sehen ist."],
        ["s-register", "Register", "<b>Club</b> = alles rund um den Club, <b>Meins</b> = deine eigenen Sachen, <b>Technik</b> = Update, freigegebene Programme und Sicherheits-Check. Die Zahl zeigt, wie viele Kacheln darin sind. Beim Wechsel läuft kurz ein heller Rahmen um das gewählte Register (<b>Ameisenlauf</b>), danach bleibt er ruhig stehen. Kacheln lassen sich festhalten und verschieben."]] },
    ] },
  { titel: "3. Nachrichten", unter: "Chats, Schreiben, Haken, wichtige Nachrichten, Vorlesen, Archivieren", bild: "nachrichten",
    legende: [["＋ Neu", "neue Nachricht an ein Mitglied"], ["Gruppe", "eine Gruppe anlegen"], ["Gemerkt", "deine gemerkten Nachrichten"], ["Test", "Nachricht an dich selbst (zum Ausprobieren)"], ["Chat", "einmal tippen = auswählen, doppelt = öffnen"], ["❗ Wichtig", "ungelesene wichtige Nachricht"], ["Gruppenchat", "mit Symbol und Zahl der Mitglieder"]],
    abschnitte: [
      { nr: 5, titel: "Die Chat-Liste", zeilen: [["s-chat-zeile", "Chat mit ungelesener wichtiger Nachricht", "Eine <b>orangefarbene Kante</b> links und <b>❗</b> an der Zahl zeigen: Darin wartet eine wichtige Nachricht. Die Zahl zeigt, wie viele Nachrichten ungelesen sind."]] },
      { nr: "+", titel: "Neue Gruppe", zeilen: [[null, "👥 Gruppe anlegen", "Über <b>„Gruppe“</b>: oben <b>👥 Deine Gruppen</b> (antippen = gleich hineinschreiben), darunter <b>✏️ Name &amp; Symbol</b> und <b>👤 Wer ist dabei?</b>. Jeder Bereich klappt mit dem Pfeil ▾ auf und zu, mit dem Schloss 🔒 bleibt er so – die App merkt es sich.", "neu"]] },
    ],
    weiter: [{ bild: "chat", titel: "Der Chat", legende: [["Zurück", "zur Chat-Liste"], ["Name", "mit wem du schreibst"], ["Online / Status", "ist der andere gerade da?"], ["Lautsprecher", "neue Nachrichten vorlesen 🔇/🔊"], ["Lupe", "im Chat suchen"], ["Menü ⋮", "stummschalten, Gruppe, Archiv …"], ["Nachricht", "vom anderen (links)"], ["Deine Nachricht", "rechts, mit Haken"], ["Wichtig", "orange umrandet mit „❗ WICHTIG“"], ["Antwort", "zitiert die Nachricht, auf die du antwortest"], ["Weiterleiten / Info", "↪️ weiterleiten, ℹ️ Einzelheiten"], ["Schreibfeld", "hier schreiben"], ["Senden", "Nachricht abschicken"], ["Knopfleiste", "Anlage, Sprache, Emoji, …"]],
      abschnitte: [
        { nr: 1, titel: "Kopfzeile", zeilen: [["s-chat-kopf", "Kopfzeile", "‹ zurück, der Name, 🔇/🔊 <b>Vorlesen</b>, 🔍 im Chat suchen und ⋮ das Menü (z. B. Chat stummschalten)."],
          ["s-vorlesen", "Vorlesen 🔇 / 🔊", "Antippen schaltet das Vorlesen ein (🔊): Das Handy liest neue Nachrichten im offenen Chat vor, z. B. „Erika: Kommst du Samstag?“. Nochmal antippen = aus (🔇)."]] },
        { nr: 8, titel: "Die Haken – wie bei WhatsApp", zeilen: [
          ["s-haken-1", "Ein grauer Haken", "Gesendet – aber noch <b>nicht auf dem Handy</b> des anderen angekommen."],
          ["s-haken-2", "Zwei graue Haken", "Auf dem Handy des anderen <b>angekommen</b>, aber noch nicht gelesen."],
          ["s-haken-3", "Zwei blaue Haken", "<b>Gelesen.</b> In Gruppen werden die Haken erst grau bzw. blau, wenn es für alle gilt; daneben steht klein, wie viele schon gelesen haben (z. B. 2/5)."]] },
        { nr: 9, titel: "Besondere Nachrichten", zeilen: [
          ["s-blase-wichtig", "Wichtige Nachricht", "Mit dem <b>❗-Knopf</b> unten verschickt: orange umrandet mit „❗ WICHTIG“ – beim Empfänger und bei dir. In den Infos (ℹ️) steht „Wichtigkeit: hoch“."],
          ["s-zitat", "Antwort", "Nachricht antippen → „↩️ Antworten“ (oder nach rechts wischen). Oben steht dann, worauf du antwortest."],
          ["s-blase-reaktion", "Reaktion", "Nachricht antippen und z. B. ❤️ oder 👍 wählen – die Reaktion steht unter der Nachricht."],
          ["s-na-seite", "Weiterleiten und Info", "↪️ leitet die Nachricht weiter oder kopiert sie. ℹ️ zeigt, wann gesendet, angekommen und gelesen."]] },
        { nr: 14, titel: "Die Knöpfe unter dem Schreibfeld", zeilen: [
          ["s-k-anlage", "Anlage 📎", "Foto, Datei oder Dokument anhängen."], ["s-k-mikro", "Mikrofon 🎤", "Antippen und wählen: <b>Sprachnachricht</b> (deine Stimme wird verschickt) oder <b>Diktieren</b> (das Handy schreibt mit, verschickt wird Text)."], ["s-mikro-wahl", "Sprachnachricht oder Diktieren", "Mit „Immer so“ fragt die App nicht mehr – ändern unter ⚙️ → Ansagen, Töne & Tipps → Mikrofon im Chat."],
          ["s-k-emoji", "Emoji 😊", "Öffnet über dem Schreibfeld die bunte Emoji-Auswahl – antippen setzt das Emoji in deinen Text."], ["s-k-zustell", "Benachrichtigen 🔔", "Wie der andere Bescheid bekommt: Push, E-Mail oder WhatsApp."],
          ["s-k-wichtig", "Wichtig ❗", "Die nächste Nachricht wird als <b>wichtig</b> verschickt. Schreibfeld und Knopf werden orange – nach dem Senden wieder normal."],
          ["s-wichtig-an", "So sieht „wichtig“ beim Schreiben aus", "Das Schreibfeld ist orange umrandet, der ❗-Knopf orange gefüllt."],
          ["s-k-wa", "WhatsApp", "Den Text an WhatsApp übergeben und dort verschicken."], ["s-k-waein", "Aus WhatsApp einfügen 📋", "In WhatsApp kopierte Nachrichten sauber einfügen."],
          ["s-k-bf", "Bildschirmfoto 📸", "Ein Bildschirmfoto machen und in diesen Chat schicken."], ["s-k-senden", "Senden ➤", "Schickt die Nachricht ab."],
          ["s-ow-blase", "Ohne Netz geschrieben", "Kein Internet? Die Nachricht geht nicht verloren: Sie steht als Blase mit <b>„⏳ wartet auf Netz“</b> im Chat und wird <b>automatisch gesendet</b>, sobald du wieder Netz hast (nur Text, in bestehenden Chats)."],
          ["s-rechtschreibung", "Tippfehler rot unterstrichen", "Beim Schreiben zeigt eine rote Wellenlinie Tippfehler – antippen, dann kommen Vorschläge. Das macht die Tastatur deines Handys. Keine Linie? ⚙️ → „🖍️ Tippfehler rot unterstreichen“ → <b>Prüfen</b> zeigt einen Testsatz und wie du die Prüfung einschaltest."]] },
      { nr: "+", titel: "Chats archivieren und löschen", zeilen: [
        ["s-chat-aktionen", "Einmal auf einen Chat tippen", "<b>💬 Öffnen</b>, <b>📦 Archivieren</b> (räumt ihn aus der Liste – er bleibt dort, auch wenn jemand schreibt), <b>🙈 Aus meiner Liste</b> (kommt bei einer neuen Nachricht zurück) oder <b>🗑️ Bei mir komplett löschen</b> (alle bisherigen Nachrichten weg – nur bei dir, die anderen behalten alles).", "neu"],
        ["s-chat-archiv-zeile", "📦 Archiviert", "Oben in der Chat-Liste. Antippen zeigt die archivierten Chats; die Zahl zeigt Ungelesenes. Dort holst du einen Chat mit <b>📤 Wieder aktivieren</b> zurück. Dasselbe geht auch im Chat oben über das Menü.", "neu"]] },
      ] },
      { bild: "chat-menue", titel: "Nachricht antippen – was geht alles?", text: "Eine Nachricht <b>antippen</b> öffnet dieses Menü: oben eine schnelle Reaktion (👍 ❤️ 😂 …), darunter <b>Antworten</b>, <b>Oben anheften</b>, <b>Merken</b>, <b>Kopieren</b>, <b>🔊 Vorlesen</b>, <b>Weiterleiten</b>, <b>Details</b> (wann gesendet, angekommen, gelesen) und <b>Löschen</b>. Eigene Nachrichten lassen sich 15 Minuten lang <b>bearbeiten</b>." }] },
  { titel: "4. Termine", unter: "Zu- und absagen, Mitfahren, Kalender, Terminanfragen", bild: "termine",
    legende: [["＋ Neu", "eigenen privaten Termin anlegen"], ["Drucken", "Terminliste drucken"], ["Liste / Kalender / To-do", "drei Ansichten"], ["Termin", "antippen öffnet ihn"], ["Deine Antwort", "z. B. „Du kommst“"], ["Geburtstage", "der nächsten 30 Tage"]],
    weiter: [{ bild: "termin-offen", titel: "Einen Termin öffnen", legende: [["Ich komme", "zusagen"], ["Vielleicht", "noch unsicher (mit kurzer Notiz)"], ["Kann nicht", "absagen (Grund freiwillig)"], ["Wer kommt", "Zusagen, Vielleicht, Absagen mit Namen"], ["Mitfahren", "Mitfahrt suchen oder anbieten"], ["In meinen Kalender", "Termin ins Handy übernehmen"]],
      text: "Nochmal auf die eigene Antwort tippen nimmt sie wieder zurück. Bei „Ich komme“ kannst du danach eine Mitfahrt suchen oder anbieten und Plätze buchen." },
      { bild: "erinnerung", titel: "Terminanfragen und deine Erinnerung", legende: [["Wann?", "kurz vorher: 15 Min., 30 Min., 1 Std. oder 2 Std."], ["Am Vortag", "zusätzlich am Tag davor ab 9 Uhr"], ["Push", "Mitteilung aufs Handy"], ["Handy-Kalender", "Eintrag mit Wecker – am lautesten"], ["Speichern", "fertig – jederzeit änderbar"]],
        text: "Mitglieder können dich zu einem Termin <b>anfragen</b> (Liste oben: „📨 Terminanfragen“) – du antwortest mit ✅ Ja, 🤔 Vielleicht oder ❌ Nein. Danach fragt die App, ob und wie du <b>erinnert</b> werden möchtest. Die Erinnerung gilt nur für dich. Abgesagte Anfragen stehen blass mit „🚫 abgesagt“ da.",
        abschnitte: [{ nr: "+", titel: "Die Anfrage in der Liste", zeilen: [["s-terminanfrage", "Terminanfrage", "Wer angefragt hat, wann und wo, deine Antwort und wer schon zugesagt hat. <b>⏰ Einstellen</b> ändert deine Erinnerung.", "neu"]] }] }] },
  { titel: "5. Mitglieder", unter: "Wer ist online, Status, Kontakt, Anklopfen", bild: "mitglieder",
    legende: [["Mein Status", "eigenen Status ändern"], ["Kacheln / Liste", "Ansicht umschalten"], ["Alle", "alle Mitglieder"], ["Online", "nur wer gerade da ist"], ["Gruppen", "nach Gruppe filtern"], ["Zeichen", "online · heute da · abwesend · noch nie"], ["Du", "deine eigene Kachel"], ["Online", "grüner Ring (pulsiert langsam) = gerade in der App"], ["Chat 💬", "sofort schreiben"], ["Anklopfen 👋", "kurz Bescheid geben, dass du sprechen möchtest"]],
    text: "Eine Kachel antippen zeigt Telefon, Mail und Adresse – soweit das Mitglied sie freigegeben hat. <b>Anklopfen 👋</b> geht nur, wenn der andere gerade online ist. Er kann annehmen oder kurz antworten („Bin beschäftigt“). Nach einer Minute fragt die App, ob du weiter anklopfen, eine Nachricht senden oder auflegen möchtest. Die Mitglieder-Kachel oben im Kopf öffnet direkt <b>nur die Online-Mitglieder</b>; „👥 Alle“ schaltet um. <b>Neu:</b> Bilder, 📞/🎥 auf der Kachel und die 📋 Anwesenheitstafel – siehe Teil 18." },
  { titel: "6. Pinnwand", unter: "Kurze Zettel für alle oder einzelne", bild: "pinnwand",
    legende: [["＋ Zettel", "neuen Zettel anheften (bis zu 4)"], ["Hinweis", "ein wichtiger Zettel wartet auf dich"], ["Wichtig", "rot umrandet"], ["Antworten", "auf den Zettel antworten"], ["✓ erl.", "als erledigt abhaken"], ["Gelesen", "wer deinen Zettel gelesen hat"], ["Abnehmen", "eigenen Zettel entfernen"]],
    text: "Zettel sind für <b>alle</b>, nur <b>für dich</b> oder für <b>bestimmte Personen</b>. Neue Zettel siehst du beim Öffnen der App in der Meldung <b>„👋 Schön, dass du da bist“</b> – ein Tipp auf <b>„📌 Pinnwand-Eintrag ansehen“</b> zeigt sie (Teil 19). Hast du diese Meldung ausgeschaltet, geht der neue Zettel direkt auf. Jeder darf höchstens 4 Zettel gleichzeitig anheften.",
    weiter: [{ bild: "pinnwand-hilfe", titel: "Hilfe-Aushang und Emojis", legende: [["Hilfe gesucht", "grüner Aushang – jemand sucht Helfer"], ["Ansehen & antworten", "öffnet die Zusammenfassung (Teil 12)"], ["Zettel mit Emojis", "z. B. Gute Besserung 🤒💐"]],
      text: "Offene Hilfe-Aufrufe hängen als <b>grüner Aushang</b> vorne an der Pinnwand. Ist ein neuer Aufruf da, geht beim Öffnen der App einmal die Pinnwand mit dem Hinweis „🙋 Es wird Hilfe gesucht“ auf – kam beim Öffnen schon eine andere Meldung, findest du den Aushang einfach an der Pinnwand. Der Aushang zählt nicht zu deinen 4 Zetteln.",
      abschnitte: [{ nr: 3, titel: "Emojis auf Zetteln", zeilen: [["s-pw-emoji", "Emojis einfügen", "Unter dem Textfeld eine Reihe für typische Anlässe: 🤒 💐 🍀 💪 ❤️ 🙏 🤗 🎂 🎉 👍 ☀️ 🍲 – antippen setzt das Emoji an die Stelle, an der du schreibst. <b>„😊 Mehr“</b> öffnet die volle Auswahl wie im Chat."]] }] }] },
  { titel: "7. SOS – Notfall", unter: "Notrufnummern, Notfallpass, Kontakte", bild: "sos",
    legende: [["Lebensgefahr", "sofort 112 anrufen"], ["112", "Feuerwehr und Rettungsdienst"], ["110", "Polizei"], ["Weitere Nummern", "Bereitschaftsdienst, Giftnotruf, Apotheke, Seelsorge …"]],
    text: "Beim Antippen einer Nummer fragt die App <b>einmal nach</b> – erst dann wird wirklich angerufen. So passiert nichts aus Versehen.",
    weiter: [{ bild: "sos-unten", titel: "Notfallpass und Kontakte", legende: [["Notfallpass", "Allergien, Medikamente, Blutgruppe – nur auf deinem Handy gespeichert"], ["Clubleitung", "Clubsprecher und Kassenwart schnell erreichen"], ["Mitglieder", "alle, die im Notfall erreichbar sind"], ["Du", "dein eigener Notfallkontakt – antippen zum Prüfen"]],
      text: "Trag bitte deinen <b>eigenen Notfallkontakt</b> ein (wer soll angerufen werden?). Notfallkontakte anderer sieht nur die Clubleitung. „📍 Wo bin ich?“ zeigt im Notfall die Adresse zum Vorlesen." },
      { bild: "sos-alle", titel: "SOS – Nachricht an alle", legende: [["Was ist passiert?", "kurz beschreiben – oder 🎙️ einsprechen"], ["Jetzt an alle senden", "geht sofort an alle – Push und E-Mail, auch bei „Nicht stören“"]],
        text: "Unter <b>💬 Nachrichten</b> gibt es den roten Knopf <b>🚨 SOS</b> für echte Notfälle im Club – sichtbar für den Admin und für alle, sobald er es freigegeben hat. Auf Wunsch hängst du <b>📍 deinen Standort</b> an. Bei den anderen erscheint die Meldung rot und wird vorgelesen. Zum Ausprobieren: <b>🧪 Probe nur an mich</b>." }] },
  { titel: "8. Einstellungen", unter: "Sprachansagen, Farbschemen, Benachrichtigungen, Privatsphäre – unten über „Mehr“", bilderReihe: ["s-ansagen-zeilen", "s-sprachansagen", "einst-farben"],
    abschnitte: [
      { nr: 1, titel: "Ansagen, Töne & Tipps", zeilen: [
        [null, "💡 Tipp des Tages", "Beim Öffnen <b>höchstens einmal in der Woche</b> ein kurzer Tipp. „👉 Ja, zeig mir wo“ führt direkt zur passenden Stelle."],
        [null, "🗣️ Sprachansagen", "Unter <b>„Auswählen“</b> kreuzt du an, was dein Handy ansagen soll: <b>wer online kommt</b>, neue Nachrichten, Anklopfen, Pinnwand, Helfen/Leihen/Börse, Mitfahrt, Standort mit Entfernung (Luftlinie) und Termine. <b>▶</b> spielt ein Beispiel, z. B. „Christina hat dir ein Post-it an die Pinnwand gehängt“. Am Anfang sind nur Nachrichten und Anklopfen an."],
        [null, "Wer kommt, wer geht", "Neu ankreuzbar: <b>„🚪 Jemand verlässt die App“</b> („Klaus hat die Club-App verlassen“). Kommen mehrere gleichzeitig online, gibt es <b>eine</b> Ansage – bei mehr als 3: „5 Clubkameradinnen und Kameraden sind gerade online“."],
        [null, "Wann spricht das Handy?", "Nur, solange die Köcheclub-App <b>offen</b> ist – nicht in deiner Ruhezeit und nicht für den Chat, den du gerade offen hast. Ist die App zu oder im Hintergrund, kommt der normale Push mit Ton (Android und iPhone erlauben Web-Apps im Hintergrund keine Sprache)."],
        [null, "🖍️ Tippfehler rot unterstreichen", "„Prüfen“ zeigt einen Testsatz mit zwei Fehlern und – passend zu deinem Handy – wie du die Rechtschreibprüfung einschaltest."],
        [null, "👋 Beim Öffnen zeigen, was neu ist", "Zeigt beim Öffnen auf einen Blick neue Nachrichten, Pinnwand-Einträge und wartende Spiele (Teil 19). Haken weg = aus."],
        [null, "🎤 Mikrofon im Chat", "Jedes Mal fragen, immer Sprachnachricht oder immer Diktieren."],
        [null, "🔊 Neue Nachrichten vorlesen", "Liest neue Nachrichten im offenen Chat vor (wie der Lautsprecher im Chat)."]] },
      { nr: 2, titel: "Benachrichtigungen", zeilen: [
        [null, "Push und E-Mail je Bereich", "Für Termine, Nachrichten, Abstimmungen, Dienste, Geburtstage und Pinnwand einzeln wählen: aufs Handy, per Mail oder beides."],
        [null, "🌙 Nicht stören", "Eine Ruhezeit (z. B. 22–7 Uhr) ohne Push. Anrufe kommen trotzdem durch. Dein Status zeigt dann „Ruhezeit bis …“."]] },
      { nr: 3, titel: "Privatsphäre", zeilen: [
        [null, "Online und „zuletzt da“", "Ob andere sehen, dass du online bist bzw. wann du zuletzt da warst. Ausgeschaltet siehst du es bei anderen auch nicht – wie bei WhatsApp."],
        [null, "Anklopfen erlauben", "Ob andere bei dir anklopfen dürfen, wenn du online bist."],
        [null, "Geburtstag, Kontaktdaten", "Was andere von dir sehen dürfen – nichts wird ohne dein Einverständnis gezeigt."]] },
      { nr: 4, titel: "Darstellung", zeilen: [[null, "Lieblingsfarbe und Ansicht", "Farbe der App, Tag/Nacht und einfache oder erweiterte Ansicht."],
        [null, "✨ Animierte Knöpfe", "An: Kacheln zoomen kurz beim Antippen, Reiter und „＋ Neu“ leuchten auf, der Online-Ring pulsiert. Aus: alles bleibt ruhig. Zu finden in der <b>erweiterten Ansicht</b> unter ⚙️ → 🎨 Darstellung; gilt für dieses Gerät.", "neu"],
        [null, "🎨 Weitere Farbschemen", "Unter den 8 bekannten Farben klappt „Weitere Farbschemen“ 8 ruhige Töne auf: Toskana, Weinberg, Salbei, Lavendel, Ocker, Schokolade, Petrol, Rosé."],
        ["s-farben-bunt", "✨ Ausgefallene Farbschemen", "6 Schemen mit Farbverlauf oben: Sonnenuntergang, Polarlicht, Kirschblüte, Tiefsee, Glut, Retro 70er. Antippen – die App färbt sich sofort um."]] },
      { nr: 5, titel: "Über die App", zeilen: [["s-ueber-app", "👨‍🍳 Über die App", "Wer die Club-App gebaut hat – mit Foto und Lebenslauf. Unter <b>⚙️ Mehr → ℹ️ App-Info → „Über den Entwickler“</b> (einfache Ansicht: „👨‍🍳 Über die App“). Mit <b>💬 Hansi schreiben</b> erreichst du ihn direkt.", "neu"]] },
      { nr: "+", titel: "Bereiche auf- und zuklappen", zeilen: [[null, "▾ Alle auf / ▴ Alle zu", "Oben rechts unter der Überschrift: ein Tipp öffnet <b>alle</b> Bereiche, danach heißt der Knopf „▴ Alle zu“ und klappt alle wieder zu.", "neu"],
        [null, "🔓 / 🔒 Schloss", "Mit dem Schloss stellst du einen Bereich fest – er bleibt offen oder zu, auch bei „Alle auf / Alle zu“. Nochmal antippen löst ihn wieder."]] },
    ] },
  { titel: "9. Notbetrieb", unter: "Wenn der Server einmal ausfällt", bild: "notbetrieb",
    legende: [["Oranges Band", "die App läuft gerade im Notbetrieb"]],
    abschnitte: [{ nr: 1, titel: "Was im Notbetrieb geht", zeilen: [
      ["s-not-band", "Notbetrieb", "Fällt der Club-Server aus, schaltet die App <b>von selbst</b> auf einen Ersatz-Server um. Oben steht das orange Band mit der Uhrzeit des Stands."],
      [null, "Ansehen geht", "Termine, Mitglieder, SOS, Dienste, Pinnwand und Nachrichten – so, wie es zuletzt war."],
      [null, "Schreiben wird gespeichert", "Nachrichten in bestehenden Chats, Zu- und Absagen, Status und Zettel werden gespeichert (⏳ „wartet“) und <b>automatisch übertragen</b>, sobald alles wieder läuft."],
      [null, "Geht gerade nicht", "Fotos und Anlagen, neue Chats, Anrufe und Push. Die Notrufnummern (112 …) gehen <b>immer</b>."],
      [null, "Zurück", "Ist der Server wieder da, verschwindet das Band von selbst und alles Gespeicherte wird übertragen."]] }] },
  { titel: "10. Fotos & Alben", unter: "Eigene Fotoalben mit Namen – z. B. „Weihnachtsmarkt 2026“", bild: "fotos-auswahl",
    legende: [["Neues Album", "Fotos auswählen und ein Album anlegen"], ["Album", "antippen öffnet es – 👥 für alle, 🔒 nur für dich"], ["Auswahl", "„☑️ Auswählen“ / „Auswahl beenden“"], ["Ins Album", "die angehakten Fotos in ein Album legen"]],
    text: "So geht’s: im Fotoalbum auf <b>„☑️ Auswählen“</b> tippen, Fotos anhaken und <b>„📸 Ins Album“</b>. Ein Album ist nur eine Sammlung – die Fotos bleiben im Fotoalbum und brauchen keinen zusätzlichen Platz.",
    abschnitte: [{ nr: 4, titel: "In welches Album?", zeilen: [["s-album-wahl", "Album wählen oder neu anlegen", "Ein vorhandenes Album antippen oder <b>„＋ Neues Album …“</b>: Namen eingeben und festlegen, ob <b>alle Mitglieder</b> es sehen oder <b>nur du</b>."]] }] },
  { titel: "11. Archiv & Chronik", unter: "Dein eigener Ordner, Fotoalben im Regal und die Clubchronik zum Blättern", bild: "archiv-regal",
    legende: [["Mein Ordner", "nur du siehst ihn – mit 🔓 kannst du anderen etwas auf Zeit freigeben"], ["Album", "deine Fotoalben stehen auch im Regal"], ["Clubchronik", "die Geschichte des Clubs"]],
    text: "Legt jemand anderes etwas in deinen Ordner (z. B. die Clubleitung eine Bestätigung), steht es dort erst <b>„zur Prüfung“</b> – du nimmst es an oder lehnst es ab.",
    weiter: [{ bild: "chronik-ordner", titel: "Die Clubchronik", legende: [["Blättern", "die Chronik wie ein Buch ansehen"], ["So füllen wir …", "kurze Anleitung, was hineingehört"], ["Beitrag einreichen", "Foto, Zeitungsartikel oder Dokument einreichen – die Clubleitung prüft und nimmt es auf"]],
      text: "Register wie Gründung, Presse, Rekorde & Höhepunkte, Feste & Jubiläen oder In Gedenken ordnen die Einträge." },
      { bild: "chronik-blaettern", titel: "Blättern", legende: [["Schließen", "zurück zur App"], ["Umblättern", "‹ › antippen oder wischen"], ["Register", "springt direkt zu einem Teil, unten zeigt der Balken, wo du bist"]],
      text: "Blättern geht in jedem Ordner im Archiv – Fotos, PDF und Dokumente erscheinen als Seiten." }] },
  { titel: "12. Helfen & Leihen", unter: "Hilfe suchen, helfen, „nach Absprache“ – über die Kachel „🤝 Helfen & Leihen“", bild: "hilfe-form",
    legende: [["Wobei?", "Art der Hilfe – bei „Sonstiges“ kurz eintragen"], ["Nach Absprache", "kein fester Tag – ihr macht den Termin miteinander aus"], ["Egal wie viele", "keine Grenze, jede Zusage zählt"]],
    text: "„🙋 Ich suche Hilfe“ öffnet dieses Formular. Bei <b>„📅 Bestimmter Tag“</b> wählst du Tag und Zeit, bei <b>„🤝 Nach Absprache“</b> bleibt der Aufruf 30 Tage offen. Bei <b>„📣 Wie möchtest du es veröffentlichen?“</b> wählst du selbst: <b>📌 Pinnwand</b> (grüner Aushang), <b>🔔 Push</b> und/oder <b>✉️ E-Mail</b> – mehrere gehen. Wählst du nichts, steht der Aufruf nur unter Helfen &amp; Leihen.",
    abschnitte: [{ nr: 4, titel: "Beschreibung", zeilen: [["s-hilfe-text", "Was genau?", "Großes Textfeld (bis 1000 Zeichen): was zu tun ist, was man mitbringen soll, wie man dich erreicht."]] }],
    weiter: [{ bild: "hilfe-kurz", titel: "Einen Aufruf antippen", legende: [["Wer sucht", "Name"], ["Wobei", "was gebraucht wird"], ["Wann", "Tag oder „nach Absprache“"], ["Gesucht", "wie viele, wie viele schon dabei"], ["Beschreibung", "die Einzelheiten"], ["Ja, ich kann helfen", "zusagen"], ["Kann nicht", "absagen"], ["Mehr Details", "Nachricht an die Person, die sucht"]],
      text: "Du siehst nur die <b>Zusammenfassung</b> – keine Eingabefelder. „❓ Ich brauche noch mehr Details“ öffnet eine Nachricht mit vorbereitetem Anfang. Antworten kannst du später zurücknehmen.",
      abschnitte: [{ nr: 1, titel: "Dein eigener Aufruf", zeilen: [["s-hilfe-eigen", "So sehen ihn die Mitglieder", "Antippen zeigt dieselbe Zusammenfassung, darunter wer zugesagt hat und wie viele noch fehlen. <b>„✏️ Ändern“</b> öffnet das Formular (kein neuer Rundruf – nur wer zugesagt hat, erfährt von einer Tag- oder Ortsänderung). <b>„🔒 Aufruf schließen“</b> beendet ihn."]] }] }] },
  { titel: "13. Bedienen, Anmelden & ohne Netz", unter: "Was überall in der App gleich funktioniert",
    abschnitte: [{ nr: 1, titel: "Zurück und Rückfragen", zeilen: [
      [null, "‹ und die Zurück-Taste", "‹ oben links und die Zurück-Taste des Handys gehen <b>einen Schritt zurück</b> – dorthin, wo du vorher warst. Ist ein Fenster offen, schließt Zurück <b>nur das Fenster</b>; was du angefangen hast, bleibt stehen."],
      ["s-rueckfrage", "Rückfragen beim Löschen", "Der rote Knopf sagt, was passiert (<b>„🗑️ Löschen“</b>, „Absagen“ …). Vorausgewählt ist immer <b>„Abbrechen“</b> – so passiert nichts aus Versehen."],
      ["s-verbindung-einfach", "Verbindung prüfen", "Lämpchen oben antippen: „✅ Verbindung in Ordnung“ oder „⚠️ Störung“. Mit „🧪 Test-Mitteilung an mich“ prüfst du, ob Mitteilungen ankommen."]] },
      { nr: 2, titel: "Ohne Internet", zeilen: [
      [null, "App ohne Netz öffnen", "Die App zeigt deinen <b>letzten Stand</b> – oben steht deutlich „📴 Kein Netz – das ist dein Stand von …“. Kommt das Netz zurück, lädt sie von selbst neu."],
      [null, "Nachrichten ohne Netz", "Werden vorgemerkt und automatisch gesendet (Teil 3)."]] },
      { nr: 3, titel: "Neues Gerät, neue Version", zeilen: [
      [null, "Einrichtungskarte", "Die Clubleitung kann dir eine Karte mit QR-Code ausdrucken: Kamera draufhalten, Link antippen – die App führt dich Schritt für Schritt. Kommt der Link aus WhatsApp oder Google Lens, sagt die App zuerst „In Safari/Chrome öffnen“."],
      [null, "Updates und Startprobleme", "Neue Versionen kommen von selbst: Holst du die App zurück und tippst gerade nichts, aktualisiert sie sich kurz. Startet sie einmal nicht, erscheint nach 12 Sekunden Hilfe mit „🧹 Speicher der App leeren“ – deine Anmeldung bleibt erhalten."]] }] },
  { titel: "14. Spiele", unter: "Köcheclub Edition – gegen den Computer oder gegen Mitglieder", bild: "spiele",
    legende: [["Tic-Tac-Toe", "🍅 gegen 🥦 – drei (bei 4 × 4 vier) in einer Reihe"], ["Schach", "mit der Küchenbrigade: Küchenchef = König, Kaltmamsell = Dame …"], ["Bauernskat", "zu zweit mit französischem Blatt – nach Köcheclub-Regeln (Teil 19)"], ["Küchenterror", "Küchenquiz auf Zeit – 20, 15 oder 10 Sekunden je Frage"]],
    text: "Die Kachel <b>🎲 Spiele</b> findest du im Register <b>Club</b>. Tippe auf ein Spiel und wähle <b>🤖 Gegen den Computer</b> (mit Stärke) oder <b>👥 Gegen Mitglieder</b>.",
    abschnitte: [{ nr: "+", titel: "Spielen", zeilen: [
      ["s-ttt", "Tic-Tac-Toe", "Feld antippen – dann ist der andere dran. Wer zuerst eine Reihe hat, gewinnt.", "neu"],
      ["s-schach", "Schach", "Figur antippen, dann das Zielfeld. Spielbare Felder werden markiert. Mit 🔊 <b>Ansage</b> liest die App die Züge vor.", "neu"],
      [null, "⏸ Pause", "In jedem Spiel: „⏸ Pause“ hält an, „▶ Weiter“ geht genau dort weiter.", "neu"],
      [null, "⏱️ Schachuhr", "Bedenkzeit 5, 10 oder 15 Minuten je Spieler – oben bei „⏱️ Uhr“ oder beim Herausfordern („⏱️ Live“). Nach jedem Zug hält deine Uhr an und die des Gegners läuft; in der letzten Minute wird sie rot. Wer keine Zeit mehr hat, verliert.", "neu"]] }],
    weiter: [{ bild: "spiele-mg", titel: "Gegen Mitglieder und der Pokal", legende: [],
      text: "<b>🎲 Jemanden herausfordern</b>: Mitglied wählen – es bekommt eine Mitteilung und kann annehmen. Ihr zieht abwechselnd, du bekommst Bescheid, wenn du dran bist. Mit <b>📅 Termin vereinbaren</b> verabredet ihr euch zu einer festen Zeit. Für Siege gibt es Punkte: <b>🏆 Pokal des Monats</b> und die <b>Club-Rangliste</b>. Beim Start fragt die App <b>höchstens einmal in der Woche</b> „Lust auf eine Partie?“ – mit „Keine Spiele“ ist das aus." }] },
  { titel: "15. Hilfe & Tipps", unter: "Das „?“ unten rechts, das Hilfe-Zentrum und „Kurz erklärt“", bild: "hilfezentrum",
    legende: [["Suchfeld", "Stichwort eingeben – z. B. „Farbe“ oder „Termin“"]],
    text: "Im <b>Hilfe-Zentrum</b> stehen über 160 kurze Hilfen in Kapiteln – von „Erste Schritte“ bis „Notfall“. Jede Hilfe hat einen Knopf <b>„Zeig es mir“</b>, der gleich an die richtige Stelle springt. Alles lässt sich auch ausdrucken.",
    abschnitte: [{ nr: "+", titel: "So findest du Hilfe", zeilen: [
      ["s-frage-lupe", "„?“ und Lupe", "Unten rechts auf jeder Seite: <b>?</b> öffnet genau die Hilfen zu dem Bereich, in dem du gerade bist. Die <b>🔍 Lupe</b> sucht in der ganzen App. Lange auf das „?“ drücken blendet es aus (zurück unter ⚙️ Mehr).", "neu"],
      ["s-kurz-erklaert", "🎓 Kurz erklärt", "Beim ersten Besuch eines Bereichs erklärt eine Karte kurz, was man dort machen kann – mit <b>🔊 Vorlesen</b>. „Verstanden“ blendet sie aus, „Keine Einweisungen mehr“ für immer.", "neu"],
      [null, "👍 / 👎 Hat es geholfen?", "Unter jeder Hilfe kannst du sagen, ob sie dir weitergeholfen hat – so werden die Hilfen besser.", "neu"]] }] },
  { titel: "16. Dienstwünsche", unter: "Mit Twinkey eintragen – oder erst auf Papier", bild: "dienstwuensche",
    legende: [["Zurück zur Club-App", "Fenster schließen"], ["Leerer Bogen", "deinen persönlichen Bogen drucken oder mailen"], ["Fertig – Bestätigung", "Aufstellung per App-Nachricht und E-Mail"]],
    text: "Tippe auf <b>🗓️ Mein Dienst</b> → <b>„📝 Wünsche eintragen“</b> (in der einfachen Ansicht auf die Kachel <b>📝 Dienstwünsche</b>). Das öffnet <b>Twinkey</b> – den Assistenten aus der Dienstplanung. Er fragt Tag für Tag, wann du kannst und wann du am liebsten arbeitest. Gespeichert wird von selbst.",
    abschnitte: [{ nr: "+", titel: "Der leere Wunschbogen", zeilen: [
      ["s-bogen-seite", "Dein Bogen", "Alle Tage mit Spalten für <b>Kann</b>, <b>Wunsch</b> und <b>Sperre</b>, Seite 2 mit Bereitschaft und Anleitung. Oben dein Name und rechts ein <b>QR-Code mit deiner Mitglieds-ID</b> – daran erkennt die Planung deinen Bogen.", "neu"],
      ["s-bogen-knoepfe", "Drucken oder mailen", "<b>🖨️ Drucken</b> – oder ohne Drucker <b>✉️ Per E-Mail an mich</b>: der Bogen kommt als PDF in dein Postfach. Von Hand ausfüllen und die Zeiten danach mit Twinkey eintragen.", "neu"]] }] },
  { titel: "17. Meine Daten haben sich geändert", unter: "Neue Anschrift, Handynummer & Co. – über die Kachel „✏️ Meine Daten geändert?“ im Register Meins", bild: "meine-daten",
    legende: [],
    text: "Antippen, was sich geändert hat, und die neuen Angaben eintragen. Die Meldung geht <b>gleich an die Richtigen</b> im Club (z. B. Clubsprecher und Kassenwart) – die Zeile unter jedem Knopf zeigt, an wen. Unten siehst du deine letzten Meldungen mit dem Stand (eingegangen, gesehen, eingetragen). Ist etwas gerade nicht nötig, ist der Knopf blass." },
  { titel: "18. Neu in Version 6", unter: "Was seit der letzten Anleitung dazugekommen ist", bild: "neu-mitglieder",
    legende: [["Dein Bild", "statt Buchstaben eine Koch-Figur (Meins → 🧑‍🍳 Mein Bild)"], ["Der kleine Punkt", "✓ grün = gerade online · blau = heute da · orange = abwesend · grau = länger nicht da"], ["📞 Anrufen", "nur hell, wenn das Mitglied gerade online ist"], ["🎥 Videoanruf", "ebenso – beide brauchen die App offen"]],
    text: "Bei den <b>👥 Mitgliedern</b> siehst du jetzt die Bilder der anderen. Der grüne Ring (er pulsiert langsam) und der kleine Punkt unten rechts zeigen, ob jemand gerade da ist. Anrufen und Videoanruf gehen direkt von der Kachel.",
    weiter: [
      { bild: "neu-tafel", titel: "Die Anwesenheitstafel", legende: [["📋", "Tafel einschalten (🔲 Kacheln, ☰ Liste)"], ["Lämpchen", "grün = gerade online, blau = heute da, orange = abwesend, grau = länger nicht da"], ["Name", "antippen öffnet das Mitglied"]],
        text: "Die Tafel zeigt nur <b>Namen und Lämpchen</b> – wer online ist, steht oben. Ein Tipp auf einen Namen öffnet das Mitglied; dort kannst du schreiben, anklopfen oder anrufen. Die Ansicht wählst du auch unter ⚙️ → Darstellung.",
        abschnitte: [
      { nr: "+", titel: "Bilder", zeilen: [
        ["s-mein-bild", "🧑‍🍳 Mein Bild", "Register <b>Meins</b> → <b>„🧑‍🍳 Mein Bild“</b>: 40 Koch-Figuren zur Auswahl, viele Köche auch mit Schnauzer. „Kein Bild“ bringt deine Buchstaben zurück.", "neu"],
        ["s-mitglied-bild", "Bild beim Mitglied", "Öffnest du ein Mitglied, steht sein Bild ganz oben.", "neu"],
        ["s-bild-gross", "Bild groß ansehen", "Ein Tipp aufs Bild zeigt es groß; noch ein Tipp schließt es.", "neu"]] },
      { nr: "+", titel: "Nachrichten", zeilen: [
        ["s-pfeil-menue", "Mehr am Pfeil", "Der kleine Pfeil neben einer Nachricht: <b>↪️ Weiterleiten, 📋 Kopieren, ✂️ Ausschneiden, 🗄️ Archivieren</b> (in deinen eigenen Ordner) und <b>🗑️ Löschen</b>. Bei deinen eigenen Nachrichten außerdem <b>❗ Wichtig</b> – auch nachträglich (orangefarbener Rahmen für alle, ohne neue Benachrichtigung).", "neu"],
        ["s-chat-ganz", "Ganzer Chat", "Im Chat oben <b>⋮</b> → <b>„Ganzer Chat“</b>: 📋 Kopieren, 🖨️ Ausdrucken oder 🗄️ in dein Archiv legen.", "neu"],
        [null, "Abstimmung nur für einige", "Beim Anlegen einer Abstimmung fragt die App <b>„An wen?“</b>: alle, eine Gruppe oder eine Auswahl. Nur die Gefragten sehen sie und das Ergebnis.", "neu"]] },
      { nr: "+", titel: "Meins", zeilen: [
        [null, "🗓️ Mein Dienst", "Eine Kachel für alles rund um den Dienst (erweiterte Ansicht): <b>📝 Wunschplan</b> (abgegeben oder übernommen), <b>📅 Sollplan</b> (deine nächsten Dienste) und <b>⏱️ Istplan</b> (wann du wirklich da warst).", "neu"],
        [null, "🔐 Meine Daten", "Zeigt, was die App über dich gespeichert hat – Angaben, Zugang, Rechte, Benachrichtigungen. Zum Ausdrucken oder als Datei; stimmt etwas nicht, meldest du es gleich dort.", "neu"],
        [null, "Kacheln kleiner", "In der erweiterten Ansicht: ⚙️ → Darstellung → <b>„🔲 Kacheln auf der Startseite“</b> → „Klein“ – dann passen 3 nebeneinander.", "neu"]] },
      { nr: "+", titel: "Bedienen und Hilfe", zeilen: [
        [null, "✅ Grüner Haken oben", "In langen Fenstern erscheint oben links ein grüner ✓, wenn der Knopf zum Übernehmen weit unten steht. Ein Tipp darauf wirkt wie der Knopf – kein Wischen nötig.", "neu"],
        [null, "„＋ Neu“ leuchtet kurz", "Kommst du auf eine Seite, leuchtet der Knopf „＋ Neu“ oben kurz auf – damit du siehst, wo du etwas anlegst.", "neu"],
        [null, "🤔 Unter Vorbehalt", "Schlägt dir jemand bei einer Terminanfrage eine andere Zeit vor: annehmen, <b>unter Vorbehalt</b> (mit kurzem Satz, woran es hängt) oder ablehnen.", "neu"],
        [null, "👥 Mitglieder fragen", "Weiß Twinkey nicht weiter: bei „🧑‍🍳 Frag Twinkey“ auf <b>„👥 Lieber ein Mitglied fragen“</b> – an alle oder ausgewählte, per App, Push oder E-Mail.", "neu"],
        [null, "🎙️ Mikrofon-Hilfe", "Klappt Diktieren nicht, führt <b>„🧭 Schritt für Schritt helfen“</b> im Mikrofon-Fenster durch alle Einstellungen deines Handys.", "neu"],
        [null, "📨 Verbindung an Hansi", "Tipp oben aufs <b>Lämpchen</b>: Im Fenster stehen die Messwerte. <b>„📨 Ergebnis an Hansi senden“</b> schickt sie ihm (nur Technik-Werte), 🖨️ druckt sie aus.", "neu"]] },
        ] },
    ] },
  { titel: "19. Neu in Version 7", unter: "Was seit Version 6 dazugekommen ist", bild: "neu7-wasneu",
    legende: [["Was ist neu?", "neue Nachrichten (in Chats und Gruppen), Pinnwand-Einträge, wartende Spiele"], ["💬 Direkt zu den Nachrichten", "öffnet die Chats"], ["📌 Pinnwand-Eintrag ansehen", "zeigt die neuen Zettel"], ["🎲 Zu den Spielen", "Einladung annehmen oder weiterspielen"], ["🔕 Diese Meldung ausschalten", "kommt dann nicht mehr"]],
    text: "Öffnest du die App und es gibt Neues, begrüßt sie dich mit <b>„👋 Schön, dass du da bist“</b> und zeigt auf einen Blick, was seit deinem letzten Besuch dazugekommen ist – mit Knopf direkt dorthin. „Später“ schließt das Fenster. Wieder einschalten: <b>⚙️ Einstellungen → 🗣️ Ansagen, Töne &amp; Tipps → „👋 Beim Öffnen zeigen, was neu ist“</b>.",
    abschnitte: [{ nr: "+", titel: "Weniger Fenster beim Öffnen", zeilen: [
      [null, "Höchstens ein Hinweis-Fenster", "Beim Öffnen kommt <b>höchstens ein</b> Hinweis-Fenster – nicht mehrere hintereinander. Fenster, auf die du antworten musst (z. B. ein Notfall oder eine Terminanfrage), kommen wie bisher.", "neu"],
      [null, "💡 Tipp und 🎲 Spiele-Einladung", "Der Tipp des Tages und die Frage „Lust auf eine Partie?“ kommen <b>höchstens einmal in der Woche</b>.", "neu"],
      [null, "🔧 Kleine Systemverbesserungen", "Die App wird laufend ein wenig besser. Das kommt von selbst beim Öffnen – du musst nichts tun.", "neu"]] }],
    weiter: [
      { bild: "neu7-bsk", titel: "🃏 Bauernskat nach Köcheclub-Regeln", legende: [["Trumpf ansagen", "Vorhand wählt eine Farbe oder Grand (nur Buben)"], ["Häufchen des Gegners", "8 Häufchen: unten verdeckt, oben offen"], ["Trumpf", "was angesagt ist und wer angesagt hat"], ["Deine Häufchen", "eine offene Karte antippen = ausspielen"]],
        text: "Jeder hat <b>8 Häufchen</b> auf dem Tisch: unten eine verdeckte Karte, oben eine offene. Vor jedem Spiel siehst du, wie <b>gemischt und ausgeteilt</b> wird (ein Tipp auf den Tisch = gleich fertig). Wer gibt, <b>wechselt</b> jedes Spiel. <b>Vorhand</b> sieht ihre offenen Karten und <b>sagt Trumpf an</b>, dann spielt sie aus. Spielst du eine Karte, wird die Karte darunter sofort aufgedeckt. Wer angesagt hat, braucht <b>61 Augen</b>. Alles Weitere unter <b>„📖 Regeln kurz“</b> im Spiel.",
        abschnitte: [
      { nr: "+", titel: "👑 Gruppen-Admins und 📋 Meine Gruppen", zeilen: [
        ["s-gruppen-admin", "👑 Weitere Gruppen-Admins", "Im Gruppen-Chat oben <b>⋮</b> → <b>„✏️ Gruppe bearbeiten“</b> (auch beim Anlegen einer Gruppe): bei einem Mitglied die <b>👑 Krone</b> antippen – farbig = Gruppen-Admin, grau = nicht. Dann <b>„💾 Speichern“</b>. Gruppen-Admins dürfen die Gruppe mit verwalten. Im Chat-Menü steht bei den Mitgliedern 👑 hinter den Admins.", "neu"],
        ["s-gruppe-uebergeben", "Gruppe beim Verlassen übergeben", "Hast du die Gruppe angelegt und tippst auf <b>„🚪 Gruppe verlassen“</b>, fragt die App <b>„👑 Wer führt die Gruppe weiter?“</b> – du wählst einen Namen, dann ist er der neue Gruppen-Admin.", "neu"],
        [null, "📋 Meine Gruppen", "Bei <b>👥 Mitglieder</b> deine eigene Kachel öffnen → <b>„📋 Meine Gruppen“</b> (oder neben den Gruppen-Knöpfen <b>„📋 Übersicht“</b>): alle Gruppen, in denen du bist, mit ihren Mitgliedern. Darunter <b>„💬 Zum Gruppen-Chat“</b> oder <b>„👥 Als Liste“</b>.", "neu"],
        [null, "👥 Gemeinsame Gruppen", "Öffnest du ein anderes Mitglied, stehen unter seinem Namen die Gruppen, in denen ihr beide seid – antippen öffnet den Gruppen-Chat.", "neu"]] },
      { nr: "+", titel: "Bedienen und Aussehen", zeilen: [
        [null, "🟢 Online-Ring pulsiert", "Der grüne Ring um Bild oder Namen eines Mitglieds, das gerade online ist, leuchtet jetzt <b>langsam auf und ab</b>.", "neu"],
        [null, "✨ Animierte Knöpfe an/aus", "Wer es ruhiger mag: in der <b>erweiterten Ansicht</b> unter ⚙️ → <b>🎨 Darstellung</b> → <b>„✨ Animierte Knöpfe“</b> ausschalten. Dann zoomt und leuchtet nichts mehr, auch der Online-Ring und das Austeilen beim Bauernskat bleiben ruhig.", "neu"],
        [null, "🎤 Diktieren in mehr Feldern", "Das kleine 🎤 rechts im Feld gibt es jetzt auch in der <b>🔍 Suche</b>, im <b>Hilfe-Zentrum</b>, beim <b>Pinnwand-Zettel</b>, beim <b>Hilfe-Aufruf</b> und beim <b>Angebot</b>: antippen, sprechen – das Handy schreibt mit (wenn dein Handy das kann).", "neu"],
        [null, "Status-Pfeil in deiner Farbe", "Der kleine Pfeil unter deinem Status oben hat jetzt die <b>Farbe deines Status</b> – z. B. grün bei „verfügbar“. Antippen öffnet die Auswahl.", "neu"]] }] }] },
  { titel: "20. Neu in Version 8", unter: "Was seit Version 7 dazugekommen ist", bild: "neu8-ust",
    legende: [["🙋 Viel Hilfe, bitte", "einfache Ansicht, große Schrift, Schritt-für-Schritt-Hilfe mit Vorlesen und 🎙️ Sprachsteuerung"], ["👌 Ein bisschen Hilfe", "ein roter Rahmen zeigt Schritt für Schritt, was als Nächstes kommt"], ["😎 Danke, ich komme klar", "alles bleibt, wie es ist"]],
    text: "Die App fragt einmal: <b>„🤝 Wie viel Unterstützung möchtest du?“</b> – du tippst an, was zu dir passt, die App stellt alles passend ein. Ändern geht jederzeit: <b>⚙️ Einstellungen → „🤝 Unterstützung“ → Wählen</b>.",
    weiter: [
      { bild: "neu8-sh", titel: "👣 Schritt für Schritt", text: "Ist die Schritt-Hilfe an, zeigt ein <b>roter, pulsierender Rahmen</b>, wo du als Nächstes tippen sollst. Unten steht in einer roten Leiste, was zu tun ist – z. B. <b>„Schritt 1 von 6: Tippe oben rechts auf ‚＋ Zettel‘“</b>. Hast du es gemacht, kommt der nächste Schritt von selbst. Am Ende gibt es ein kleines Lob.",
        abschnitte: [{ nr: "+", titel: "So bedienst du die Schritt-Hilfe", zeilen: [
          [null, "🔈 Vorlesen", "Der Lautsprecher in der Leiste liest den Schritt vor. Bei „Viel Hilfe“ wird von selbst vorgelesen.", "neu"],
          [null, "Fertig – weiter ➜", "Bei Feldern, die du nicht ausfüllen musst (z. B. Beschreibung), geht es mit diesem Knopf weiter.", "neu"],
          [null, "✕ Schließen", "beendet die Hilfe für diesen Vorgang. Ganz aus- oder einschalten: ⚙️ Einstellungen → „🤝 Unterstützung“.", "neu"],
          [null, "Wo gibt es sie?", "Pinnwand, Nachrichten, Termine, Protokolle, Vorschläge, Mein Bild, Erstattung, Archiv, Mitglieder, Helfen & Leihen, Börse, Fotos, Gruppen, Dienstpläne, Einstellungen und Spiele.", "neu"]] }] },
      { bild: "neu8-sb", titel: "🎙️ Sprachsteuerung", text: "Unten links sitzt das runde <b>🎙️ Mikrofon</b>. Antippen, dann im Fenster <b>„Ich höre zu …“</b> einfach sagen, was du möchtest – z. B. <b>„Nachricht an Klaus“</b>. Gibt es mehrere Klaus, fragt die App nach; danach fragt sie, ob sie gleich <b>mitschreiben</b> soll. Zugehört wird <b>nur</b>, wenn du auf 🎙️ tippst. Im Fenster: <b>„📋 Alle Befehle“</b> und <b>„🔇 Mikro aus“</b>. <b>Lange drücken</b> auf 🎙️ fragt, ob du die Sprachsteuerung ganz ausschalten möchtest.",
        abschnitte: [{ nr: "+", titel: "Das kannst du zum Beispiel sagen", zeilen: [
          [null, "„Startseite“ / „Ich weiß nicht weiter“", "bringt dich immer zurück zur Startseite. „Zurück“ geht eine Seite zurück.", "neu"],
          [null, "„Nachricht an Klaus: Bin gleich da“", "öffnet den Chat mit Klaus, der Text steht schon drin. „Nachricht an alle: …“ bereitet eine Nachricht an alle vor – gesendet wird erst, wenn <b>du</b> auf Senden tippst.", "neu"],
          [null, "„Zettel an die Pinnwand: Schürzen abgeben“", "neuer Pinnwand-Zettel mit diesem Text.", "neu"],
          [null, "„Nächster Termin“ / „Ich komme zum Clubabend“", "sagt den nächsten Termin an bzw. sagt zu – die App fragt vorher noch einmal nach. Auch „Ich kann nicht“ und „Vielleicht“.", "neu"],
          [null, "„Lies mir die neuen Nachrichten vor“", "sagt, wer geschrieben hat, und liest vor. „Was steht auf der Pinnwand?“ liest die Zettel vor.", "neu"],
          [null, "„Ruf Klaus an“ / „Öffne den Ordner Verträge“", "ruft in der App an (wenn Klaus online ist, sonst Telefon/WhatsApp) bzw. öffnet den Ordner im Archiv.", "neu"],
          ["neu8-sbliste", "📋 Alle Befehle mit Suche", "Die Liste zeigt alle Sätze, mit Suchfeld oben. Kennt die App einen Satz noch nicht, fragt sie <b>„Was meinst du damit?“</b> – du tippst das Ziel an, und beim nächsten Mal versteht sie dich (🧠 gelernt).", "neu"]] }] },
      { bild: "neu8-klick", titel: "👆 Was kann ich antippen?", text: "Über dem <b>„?“</b> unten rechts sitzt der Knopf <b>👆</b>. Antippen – dann wird <b>alles, was man antippen kann, rot umrandet</b>. Ausschalten mit ✕ oder es geht nach 2 Minuten von selbst aus." },
      { bild: "neu8-spiele", titel: "🎲 Neue Spiele", text: "Bei <b>🎲 Spiele</b> sind dazugekommen: <b>Mensch ärgere dich nicht</b> (würfeln, rauswerfen, ins Ziel – bis zu 4 Farben), <b>Fang den Koch</b> (Würfelspiel: Zutaten sammeln, Gerichte kochen – einfach und kurz) und <b>Doppelkopf</b> (zu viert gegen drei Computer-Köche). <b>Küchenterror</b> hat 100 neue Fragen – jede Partie fängt anders an.",
    abschnitte: [
      { nr: "+", titel: "💬 Nachrichten", zeilen: [
        [null, "Immer derselbe Chat", "„💬 Nachricht in der App“ öffnet den <b>vorhandenen</b> Chat mit dieser Person – mit allen bisherigen Nachrichten. Auch „📝 Korrektur meiner Daten“ landet dort.", "neu"],
        [null, "Mehreren einzeln schreiben", "In der Chat-Übersicht einen Chat <b>lange drücken</b> = markieren ✓, weitere antippen, dann „＋ Neu“: jeder markierte Chat bekommt die Nachricht <b>einzeln</b>.", "neu"],
        [null, "Anhang-Vorschau", "Ein Bild oder Dokument über dem Schreibfeld zeigt ein kleines Vorschaubild – antippen öffnet es groß (✅ Behalten / 🗑️ Entfernen).", "neu"],
        [null, "⚠️ Vertrauliches", "Schickst du etwas Vertrauliches (z. B. einen Vertrag) und es sind auch Nicht-Mitglieder dabei, fragt die App vorher nach.", "neu"],
        [null, "📊 Meine Nachrichten-Statistik", "Im Chat oben ⋮: wie viele Mails, Push und Nachrichten du bekommen und geschrieben hast – nur Anzahl und Zeit, keine Inhalte.", "neu"],
        [null, "Push mit Absender", "Die Benachrichtigung sagt jetzt, wer dir geschrieben hat – z. B. „Klaus hat dir eine Nachricht geschickt“.", "neu"]] },
      { nr: "+", titel: "🗄️ Archiv & Ordner", zeilen: [
        [null, "🗂️ Inhaltsverzeichnis", "Im Archiv (und im Büro) der Knopf <b>„🗂️ Inhaltsverzeichnis“</b>: eine Übersicht als PDF, was in deinen Ordnern liegt – zum Ausdrucken und vorn in den Ordner legen. Wahlweise privat und öffentlich getrennt.", "neu"],
        [null, "💡 Ablage-Vorschlag", "Legst du ein Dokument, Foto oder einen Vertrag ab, schlägt die App vor, wohin es gehört – z. B. „Ordner Verträge, Register …“. Du bestätigst oder wählst selbst.", "neu"],
        [null, "📋 Kopieren / ➡️ Verschieben", "Ein Dokument antippen: „Kopieren nach …“ oder „Verschieben nach …“ – mit Vorschlag.", "neu"]] },
      { nr: "+", titel: "✏️ Meine Daten", zeilen: [
        [null, "📮 Gemeldet – noch nicht eingetragen", "Hast du eine Änderung gemeldet, steht sie in <b>Meine Daten</b> mit ihrem Stand (⏳ gemeldet / 👍 freigegeben). Wird sie freigegeben, bekommst du eine kurze Push-Nachricht.", "neu"],
        [null, "💬 Rückfragen?", "Bei jeder noch offenen Meldung: der Knopf öffnet direkt den Chat mit dem, der sie bearbeitet – der Anfang „Rückfrage zu meiner Änderung …“ steht schon drin.", "neu"],
        [null, "🆘 Notfallkontakt", "Bitte <b>nicht dich selbst</b> eintragen, sondern eine <b>andere Person</b>, die im Notfall benachrichtigt werden soll – z. B. Ehefrau, Sohn, Tochter oder Nachbar. Trägst du doch deinen Namen ein, fragt die App nach.", "neu"]] },
      { nr: "+", titel: "Sonst noch neu", zeilen: [
        [null, "🔢 Anmelden auf iPhone/iPad", "Erst die Kochmütze auf den Home-Bildschirm legen, dann den Code dort eingeben – ein Code reicht. Beim Anmelden dreht sich die Kochmütze, bis die App startet.", "neu"],
        [null, "⏳ Warten mit Bild", "Dauert etwas einen Moment, zeigt die App kleine Küchen-Bilder (z. B. ein Schneebesen, der rührt) statt einer Sanduhr.", "neu"],
        [null, "🐢 Sparmodus", "Bei langsamem Netz oder schwachem Handy schaltet die App von selbst Bewegungen ab und lädt seltener nach – im Kopf steht dann 🐢. Ein-/ausschalten: ⚙️ → 🎨 Darstellung.", "neu"],
        [null, "🔄 Kochjacke jeden Tag", "Bei 🧑‍🍳 Mein Bild: „Kochjacke wechselt jeden Tag“ – Montag weiß, Dienstag schwarz … bis Sonntag hellblau.", "neu"],
        [null, "💐 Willkommen", "Meldet sich ein neues Mitglied zum ersten Mal an, hängt die App einen Willkommens-Zettel an die Pinnwand.", "neu"]] }] }] },
];
