// Inhalt der Club-App-Anleitung (Texte). Bilder: bild/<name>.png (ganze Seite) und bild/s-<name>.png (Ausschnitt).
export const VERSION = { anleitung: 3, app: "2.1.1", stand: "03.10.2026" };
export const INHALT = [
  ["So fängst du an", "in 5 Schritten"], ["1. Startseite", "einfache Ansicht – das Wichtigste auf einen Blick"], ["2. Erweiterte Ansicht", "alle Funktionen, Anzeigen im Kopf"],
  ["3. Nachrichten", "Chats, Schreiben, Diktieren, Tippfehler, wichtige Nachrichten"], ["4. Termine", "zu- und absagen, Mitfahren, Kalender"], ["5. Mitglieder", "wer ist online, Status, Kontakt, Anklopfen"],
  ["6. Pinnwand", "kurze Zettel für alle oder einzelne"], ["7. SOS – Notfall", "Notrufnummern, Notfallpass, Kontakte"], ["8. Einstellungen", "Sprachansagen, Farbschemen, Benachrichtigungen, Privatsphäre"],
  ["9. Notbetrieb", "wenn der Server einmal ausfällt"], ["10. Fotos & Alben", "eigene Alben mit Namen"], ["11. Archiv & Chronik", "dein Ordner, die Clubchronik zum Blättern"],
  ["12. Helfen & Leihen", "Hilfe suchen, helfen, „nach Absprache“"], ["13. Bedienen, Anmelden & ohne Netz", "Zurück-Taste, Rückfragen, neues Gerät, kein Internet"],
];
export const GUT_ZU_WISSEN = [
  "<b>Gut zu wissen:</b> Alle Bilder zeigen <b>Beispieldaten</b> – Namen wie „Max Mustermann“ und alle Telefonnummern sind erfunden. In deiner App stehen die echten Mitglieder und Termine.",
  "Die App hat eine <b>einfache</b> und eine <b>erweiterte Ansicht</b> – Umschalten geht jederzeit (Teil 1 und 2).",
  "Die Farben kannst du in den Einstellungen ändern („Lieblingsfarbe“) – es gibt jetzt <b>22 Farbschemen</b>. Die Bilder zeigen „Köcheclub Klassik“ am Tag.",
  "<b>Neu in Version 3</b> (mit <span class=\"neu\">NEU</span> markiert): Anmelden mit Code, Hilfe-Aushang an der Pinnwand, Emojis auf Zetteln, Nachrichten ohne Netz, klarere Zurück-Taste.",
  "<b><u>Beachte:</u></b> Die Club-App ist noch eine Beta-Version. Einige Funktionen können sich mit der Zeit noch ändern, weil ständig weiterentwickelt wird.",
];
export const START_SCHRITTE = [
  ["s-ohne-link", "Persönlichen Link öffnen", "Von Hansi bekommst du einen <b>persönlichen Link</b> (per WhatsApp oder Mail) – oder eine <b>Einrichtungskarte</b> mit QR-Code: Kamera draufhalten und den Link antippen. Einfach antippen – die App öffnet sich und weiß, wer du bist. Den Link nicht weitergeben: Er ist dein Schlüssel."],
  ["@icon", "Auf den Startbildschirm legen", "Die App zeigt dir mit <b>„📲 Köcheclub als App einrichten“</b> Schritt für Schritt, was du tippen musst – passend zu deinem Handy. Kurz: <b>iPhone (Safari):</b> Teilen ⬆️ → „Zum Home-Bildschirm“. <b>Android (Chrome):</b> ⋮ → „App installieren“. Danach die App immer über das Köcheclub-Symbol öffnen."],
  ["s-kurzcode", "Mit Code anmelden", "Fragt die neue App nach einem Code: im Browser zeigt die App bei der Einrichtung einen <b>6-stelligen Code</b> – den hier eintippen. So brauchst du den langen Link nicht abzutippen. Auch für ein zweites Gerät (Tablet): ⚙️ → „🔢 Code für ein anderes Gerät“.", "neu"],
  ["s-benachr-ein", "Benachrichtigungen einschalten", "Damit Nachrichten und Termine aufs Handy kommen: unter <b>Heute wichtig</b> auf <b>Einschalten</b> tippen und erlauben."],
  ["s-status", "Status setzen", "Oben im Kopf zeigst du den anderen, ob du <b>verfügbar</b>, beschäftigt, im Urlaub, krank oder abwesend bist. Antippen und auswählen."],
];
export const TEILE = [
  { titel: "1. Startseite", unter: "Einfache Ansicht – das Wichtigste auf einen Blick", bild: "start-einfach",
    legende: [["Status", "dein Status – antippen zum Ändern"], ["Termin-Karte", "der nächste Termin mit deiner Antwort"], ["Neue Nachrichten", "Zahl der ungelesenen Nachrichten"], ["Mitglieder", "wie viele es sind und wer gerade online ist"], ["Nächster Termin", "in wie vielen Tagen"],
      ["Ansicht", "einfach oder erweitert"], ["Version", "Stand der App, Update prüfen"], ["Schnellzugriff", "die großen Kacheln"], ["Lupe", "alles in der App suchen"], ["Fußleiste", "immer unten: Start, Termine, Nachrichten, Mitglieder, Mehr"]],
    abschnitte: [
      { nr: 1, titel: "Status", zeilen: [["s-status", "Mein Status", "Zeigt den anderen, wie du gerade erreichbar bist: 🟢 verfügbar, 🟠 beschäftigt, 🏖️ Urlaub, 🤒 krank, ⚪ abwesend – auf Wunsch mit „bis“-Datum. Hast du eine Ruhezeit eingestellt, steht dort automatisch „🌙 Ruhezeit bis 07:00“."]] },
      { nr: 2, titel: "Termin-Karte und die drei Felder", zeilen: [
        ["s-termin-karte", "Termin-Karte", "Der nächste Termin mit Datum, Uhrzeit und Ort – und deine Antwort (z. B. ✅ Ich komme) mit der Zahl der Zusagen. Antippen öffnet den Termin."],
        ["s-mini0", "Neue Nachrichten", "Die Zahl der ungelesenen Nachrichten. Gibt es Neues, läuft ein <b>orangefarbener Rand</b> („Ameisenstraße“) um das Feld. Antippen öffnet die Nachrichten."],
        ["s-mini1", "Mitglieder", "Wie viele Mitglieder es gibt – daneben der <b>grüne Punkt mit der Zahl</b>, wer gerade online ist (grau = gerade niemand). <b>Antippen</b> öffnet direkt die Mitglieder-Seite <b>nur mit denen, die gerade online sind</b>.", "neu"],
        ["s-mini2", "Nächster Termin", "In wie vielen Tagen der nächste Termin ist. Ab 5 Tagen vorher läuft ein hellgrüner Rand, ab 3 Tagen ein orangefarbener, am Vortag und am Tag selbst ein roter."]] },
      { nr: 6, titel: "Ansicht, Version und Schnellzugriff", zeilen: [
        ["s-ansicht", "Einfache Ansicht", "Antippen schaltet zur <b>erweiterten Ansicht</b> mit allen Funktionen (Teil 2). Zurück geht es genauso."],
        ["s-version", "Version", "Zeigt die App-Version. Antippen prüft, ob es ein Update gibt. Updates kommen sonst von selbst – ein Hinweis fragt dann kurz nach."],
        ["s-kachel0", "Termine", "Alle Termine, zu- und absagen (Teil 4)."], ["s-kachel1", "Nachrichten", "Chats mit einzelnen Mitgliedern und Gruppen (Teil 3). Die Zahl zeigt Ungelesenes."],
        ["s-kachel2", "Pinnwand", "Kurze Zettel für alle oder einzelne (Teil 6). Die Zahl zeigt neue Zettel."], ["s-kachel3", "Mein Dienst", "Deine Dienste aus dem Dienstplan."],
        ["s-kachel4", "Mitglieder", "Alle Mitglieder mit Status, Amt und Kontakt (Teil 5)."], ["s-kachel5", "Meine Dokumente", "Anleitungen und Unterlagen – öffnen sich direkt in der App mit „‹ Zurück zur App“, Drucken und Teilen. Auch diese Anleitung."],
        ["s-kachel6", "SOS – Notfall", "Notrufnummern und Kontakte im Notfall (Teil 7)."],
        ["s-heute-wichtig", "Heute wichtig", "Was heute für dich ansteht: neue Nachrichten, offene Abstimmungen, Hinweise. Antippen führt direkt hin."],
        ["s-mehr-funktionen", "Mehr Funktionen anzeigen", "Schaltet zur erweiterten Ansicht."], ["s-app-schliessen", "App schließen", "Beendet die App sauber."]] },
      { nr: 9, titel: "Lupe und Fußleiste", zeilen: [
        ["s-lupe", "Lupe", "Sucht in Nachrichten, Terminen, Pinnwand, Archiv und mehr – schon ab 2 Buchstaben."],
        ["s-fuss", "Fußleiste", "Immer unten zu sehen: <b>Start</b>, <b>Termine</b>, <b>Nachrichten</b>, <b>Mitglieder</b> und <b>Mehr</b> (Einstellungen). Die roten Zahlen zeigen Neues, die grüne Zahl, wer online ist."]] },
    ] },
  { titel: "2. Erweiterte Ansicht", unter: "Alle Funktionen und die Anzeigen im Kopf", bild: "start-erweitert",
    legende: [["Lämpchen", "Verbindung – grün ist alles gut"], ["Tag/Nacht", "hell oder dunkel"], ["Aktualisieren", "neu laden"], ["Blättern", "nächste Karte"], ["Springen", "zur letzten Karte"], ["Punkte", "welche Karte gerade gezeigt wird"], ["Register", "Club, Meins, Technik"], ["Kacheln", "alle Funktionen"]],
    abschnitte: [
      { nr: 1, titel: "Anzeigen und Knöpfe im Kopf", zeilen: [
        ["s-leds", "Lämpchen", "Grün = <b>Verbindung in Ordnung</b> · Rot = keine Verbindung · Blau = Wartung · Grau = wird geprüft. Antippen zeigt kurz „✅ Verbindung in Ordnung“ oder „⚠️ Störung“ – mit <b>Test-Mitteilung an mich</b> und <b>Problem melden</b>. Der Punkt daneben zeigt, wer online ist.", "neu"],
        ["s-modus", "Tag/Nacht", "Schaltet zwischen hell und dunkel. Das „T“ heißt Tag, das „N“ Nacht, „A“ automatisch."],
        ["s-aktualisieren", "Aktualisieren", "Lädt alles neu vom Server."]] },
      { nr: 4, titel: "Karten im Kopf und Register", zeilen: [
        ["s-pfeile", "Blättern", "Mit ‹ › blätterst du durch die Karten im Kopf: nächster Termin, Wetter, Schnellstart und mehr. « » springen zur ersten oder letzten Karte. Wischen geht auch."],
        ["s-punkte", "Punkte", "Zeigen, welche Karte gerade zu sehen ist."],
        ["s-register", "Register", "<b>Club</b> = alles rund um den Club, <b>Meins</b> = deine eigenen Sachen, <b>Technik</b> = Update, freigegebene Programme und Sicherheits-Check. Die Zahl zeigt, wie viele Kacheln darin sind. Beim Wechsel läuft kurz ein heller Rahmen um das gewählte Register (<b>Ameisenlauf</b>), danach bleibt er ruhig stehen. Kacheln lassen sich festhalten und verschieben.", "neu"]] },
    ] },
  { titel: "3. Nachrichten", unter: "Chats, Schreiben, Haken, wichtige Nachrichten, Vorlesen", bild: "nachrichten",
    legende: [["＋ Neu", "neue Nachricht an ein Mitglied"], ["Gruppe", "eine Gruppe anlegen"], ["Gemerkt", "deine gemerkten Nachrichten"], ["Test", "Nachricht an dich selbst (zum Ausprobieren)"], ["Chat", "einmal tippen = auswählen, doppelt = öffnen"], ["❗ Wichtig", "ungelesene wichtige Nachricht"], ["Gruppenchat", "mit Symbol und Zahl der Mitglieder"]],
    abschnitte: [
      { nr: 5, titel: "Die Chat-Liste", zeilen: [["s-chat-zeile", "Chat mit ungelesener wichtiger Nachricht", "Eine <b>orangefarbene Kante</b> links und <b>❗</b> an der Zahl zeigen: Darin wartet eine wichtige Nachricht. Die Zahl zeigt, wie viele Nachrichten ungelesen sind."]] },
    ],
    weiter: [{ bild: "chat", titel: "Der Chat", legende: [["Zurück", "zur Chat-Liste"], ["Name", "mit wem du schreibst"], ["Online / Status", "ist der andere gerade da?"], ["Lautsprecher", "neue Nachrichten vorlesen 🔇/🔊"], ["Lupe", "im Chat suchen"], ["Menü ⋮", "stummschalten, Gruppe, Archiv …"], ["Nachricht", "vom anderen (links)"], ["Deine Nachricht", "rechts, mit Haken"], ["Wichtig", "orange umrandet mit „❗ WICHTIG“"], ["Antwort", "zitiert die Nachricht, auf die du antwortest"], ["Weiterleiten / Info", "↪️ weiterleiten, ℹ️ Einzelheiten"], ["Schreibfeld", "hier schreiben"], ["Senden", "Nachricht abschicken"], ["Knopfleiste", "Anlage, Sprache, Emoji, …"]],
      abschnitte: [
        { nr: 1, titel: "Kopfzeile", zeilen: [["s-chat-kopf", "Kopfzeile", "‹ zurück, der Name, 🔇/🔊 <b>Vorlesen</b>, 🔍 im Chat suchen und ⋮ das Menü (z. B. Chat stummschalten)."],
          ["s-vorlesen", "Vorlesen 🔇 / 🔊", "Antippen schaltet das Vorlesen ein (🔊): Das Handy liest neue Nachrichten im offenen Chat vor, z. B. „Erika: Kommst du Samstag?“. Nochmal antippen = aus (🔇)."]] },
        { nr: 8, titel: "Die Haken – wie bei WhatsApp", zeilen: [
          ["s-haken-1", "Ein grauer Haken", "Gesendet – aber noch <b>nicht auf dem Handy</b> des anderen angekommen."],
          ["s-haken-2", "Zwei graue Haken", "Auf dem Handy des anderen <b>angekommen</b>, aber noch nicht gelesen."],
          ["s-haken-3", "Zwei blaue Haken", "<b>Gelesen.</b> In Gruppen werden die Haken erst grau bzw. blau, wenn es für alle gilt; daneben steht klein, wie viele schon gelesen haben (z. B. 2/5)."]] },
        { nr: 9, titel: "Besondere Nachrichten", zeilen: [
          ["s-blase-wichtig", "Wichtige Nachricht", "Mit dem <b>❗-Knopf</b> unten verschickt: orange umrandet mit „❗ WICHTIG“ – beim Empfänger und bei dir. In den Infos (ℹ️) steht „Wichtigkeit: hoch“."],
          ["s-zitat", "Antwort", "Nachricht antippen → „↩️ Antworten“ (oder nach rechts wischen). Oben steht dann, worauf du antwortest."],
          ["s-blase-reaktion", "Reaktion", "Nachricht antippen und z. B. ❤️ oder 👍 wählen – die Reaktion steht unter der Nachricht."],
          ["s-na-seite", "Weiterleiten und Info", "↪️ leitet die Nachricht weiter oder kopiert sie. ℹ️ zeigt, wann gesendet, angekommen und gelesen."]] },
        { nr: 14, titel: "Die Knöpfe unter dem Schreibfeld", zeilen: [
          ["s-k-anlage", "Anlage 📎", "Foto, Datei oder Dokument anhängen."], ["s-k-mikro", "Mikrofon 🎤", "Antippen und wählen: <b>Sprachnachricht</b> (deine Stimme wird verschickt) oder <b>Diktieren</b> (das Handy schreibt mit, verschickt wird Text).", "neu"], ["s-mikro-wahl", "Sprachnachricht oder Diktieren", "Mit „Immer so“ fragt die App nicht mehr – ändern unter ⚙️ → Ansagen, Töne & Tipps → Mikrofon im Chat.", "neu"],
          ["s-k-emoji", "Emoji 😊", "Öffnet über dem Schreibfeld die bunte Emoji-Auswahl – antippen setzt das Emoji in deinen Text."], ["s-k-zustell", "Benachrichtigen 🔔", "Wie der andere Bescheid bekommt: Push, E-Mail oder WhatsApp."],
          ["s-k-wichtig", "Wichtig ❗", "Die nächste Nachricht wird als <b>wichtig</b> verschickt. Schreibfeld und Knopf werden orange – nach dem Senden wieder normal."],
          ["s-wichtig-an", "So sieht „wichtig“ beim Schreiben aus", "Das Schreibfeld ist orange umrandet, der ❗-Knopf orange gefüllt."],
          ["s-k-wa", "WhatsApp", "Den Text an WhatsApp übergeben und dort verschicken."], ["s-k-waein", "Aus WhatsApp einfügen 📋", "In WhatsApp kopierte Nachrichten sauber einfügen."],
          ["s-k-bf", "Bildschirmfoto 📸", "Ein Bildschirmfoto machen und in diesen Chat schicken."], ["s-k-senden", "Senden ➤", "Schickt die Nachricht ab."],
          ["s-ow-blase", "Ohne Netz geschrieben", "Kein Internet? Die Nachricht geht nicht verloren: Sie steht als Blase mit <b>„⏳ wartet auf Netz“</b> im Chat und wird <b>automatisch gesendet</b>, sobald du wieder Netz hast (nur Text, in bestehenden Chats).", "neu"],
          ["s-rechtschreibung", "Tippfehler rot unterstrichen", "Beim Schreiben zeigt eine rote Wellenlinie Tippfehler – antippen, dann kommen Vorschläge. Das macht die Tastatur deines Handys. Keine Linie? ⚙️ → „🖍️ Tippfehler rot unterstreichen“ → <b>Prüfen</b> zeigt einen Testsatz und wie du die Prüfung einschaltest.", "neu"]] },
      ] },
      { bild: "chat-menue", titel: "Nachricht antippen – was geht alles?", text: "Eine Nachricht <b>antippen</b> öffnet dieses Menü: oben eine schnelle Reaktion (👍 ❤️ 😂 …), darunter <b>Antworten</b>, <b>Oben anheften</b>, <b>Merken</b>, <b>Kopieren</b>, <b>🔊 Vorlesen</b>, <b>Weiterleiten</b>, <b>Details</b> (wann gesendet, angekommen, gelesen) und <b>Löschen</b>. Eigene Nachrichten lassen sich 15 Minuten lang <b>bearbeiten</b>." }] },
  { titel: "4. Termine", unter: "Zu- und absagen, Mitfahren, Kalender", bild: "termine",
    legende: [["＋ Neu", "eigenen privaten Termin anlegen"], ["Drucken", "Terminliste drucken"], ["Liste / Kalender / To-do", "drei Ansichten"], ["Termin", "antippen öffnet ihn"], ["Deine Antwort", "z. B. „Du kommst“"], ["Geburtstage", "der nächsten 30 Tage"]],
    weiter: [{ bild: "termin-offen", titel: "Einen Termin öffnen", legende: [["Ich komme", "zusagen"], ["Vielleicht", "noch unsicher (mit kurzer Notiz)"], ["Kann nicht", "absagen (Grund freiwillig)"], ["Wer kommt", "Zusagen, Vielleicht, Absagen mit Namen"], ["Mitfahren", "Mitfahrt suchen oder anbieten"], ["In meinen Kalender", "Termin ins Handy übernehmen"]],
      text: "Nochmal auf die eigene Antwort tippen nimmt sie wieder zurück. Bei „Ich komme“ kannst du danach eine Mitfahrt suchen oder anbieten und Plätze buchen." }] },
  { titel: "5. Mitglieder", unter: "Wer ist online, Status, Kontakt, Anklopfen", bild: "mitglieder",
    legende: [["Mein Status", "eigenen Status ändern"], ["Kacheln / Liste", "Ansicht umschalten"], ["Alle", "alle Mitglieder"], ["Online", "nur wer gerade da ist"], ["Gruppen", "nach Gruppe filtern"], ["Zeichen", "online · heute da · abwesend · noch nie"], ["Du", "deine eigene Kachel"], ["Online", "grüner Ring = gerade in der App"], ["Chat 💬", "sofort schreiben"], ["Anklopfen 👋", "kurz Bescheid geben, dass du sprechen möchtest"]],
    text: "Eine Kachel antippen zeigt Telefon, Mail und Adresse – soweit das Mitglied sie freigegeben hat. <b>Anklopfen 👋</b> geht nur, wenn der andere gerade online ist. Er kann annehmen oder kurz antworten („Bin beschäftigt“). Nach einer Minute fragt die App, ob du weiter anklopfen, eine Nachricht senden oder auflegen möchtest. <span class=\"neu\">NEU</span> Die Mitglieder-Kachel oben im Kopf öffnet direkt <b>nur die Online-Mitglieder</b>; „👥 Alle“ schaltet um." },
  { titel: "6. Pinnwand", unter: "Kurze Zettel für alle oder einzelne", bild: "pinnwand",
    legende: [["＋ Zettel", "neuen Zettel anheften (bis zu 4)"], ["Hinweis", "ein wichtiger Zettel wartet auf dich"], ["Wichtig", "rot umrandet"], ["Antworten", "auf den Zettel antworten"], ["✓ erl.", "als erledigt abhaken"], ["Gelesen", "wer deinen Zettel gelesen hat"], ["Abnehmen", "eigenen Zettel entfernen"]],
    text: "Zettel sind für <b>alle</b>, nur <b>für dich</b> oder für <b>bestimmte Personen</b>. Wer einen neuen Zettel bekommt, sieht ihn beim Öffnen der App. Jeder darf höchstens 4 Zettel gleichzeitig anheften.",
    weiter: [{ bild: "pinnwand-hilfe", titel: "Hilfe-Aushang und Emojis", legende: [["Hilfe gesucht", "grüner Aushang – jemand sucht Helfer"], ["Ansehen & antworten", "öffnet die Zusammenfassung (Teil 12)"], ["Zettel mit Emojis", "z. B. Gute Besserung 🤒💐"]],
      text: "Offene Hilfe-Aufrufe hängen als <b>grüner Aushang</b> vorne an der Pinnwand. Ist ein neuer Aufruf da, geht beim Öffnen der App einmal die Pinnwand mit dem Hinweis „🙋 Es wird Hilfe gesucht“ auf. Der Aushang zählt nicht zu deinen 4 Zetteln.",
      abschnitte: [{ nr: 3, titel: "Emojis auf Zetteln", zeilen: [["s-pw-emoji", "Emojis einfügen", "Unter dem Textfeld eine Reihe für typische Anlässe: 🤒 💐 🍀 💪 ❤️ 🙏 🤗 🎂 🎉 👍 ☀️ 🍲 – antippen setzt das Emoji an die Stelle, an der du schreibst. <b>„😊 Mehr“</b> öffnet die volle Auswahl wie im Chat.", "neu"]] }] }] },
  { titel: "7. SOS – Notfall", unter: "Notrufnummern, Notfallpass, Kontakte", bild: "sos",
    legende: [["Lebensgefahr", "sofort 112 anrufen"], ["112", "Feuerwehr und Rettungsdienst"], ["110", "Polizei"], ["Weitere Nummern", "Bereitschaftsdienst, Giftnotruf, Apotheke, Seelsorge …"]],
    text: "Beim Antippen einer Nummer fragt die App <b>einmal nach</b> – erst dann wird wirklich angerufen. So passiert nichts aus Versehen.",
    weiter: [{ bild: "sos-unten", titel: "Notfallpass und Kontakte", legende: [["Notfallpass", "Allergien, Medikamente, Blutgruppe – nur auf deinem Handy gespeichert"], ["Clubleitung", "Clubsprecher und Kassenwart schnell erreichen"], ["Mitglieder", "alle, die im Notfall erreichbar sind"], ["Du", "dein eigener Notfallkontakt – antippen zum Prüfen"]],
      text: "Trag bitte deinen <b>eigenen Notfallkontakt</b> ein (wer soll angerufen werden?). Notfallkontakte anderer sieht nur die Clubleitung. „📍 Wo bin ich?“ zeigt im Notfall die Adresse zum Vorlesen." }] },
  { titel: "8. Einstellungen", unter: "Sprachansagen, Farbschemen, Benachrichtigungen, Privatsphäre – unten über „Mehr“", bilderReihe: ["s-ansagen-zeilen", "s-sprachansagen", "einst-farben"],
    abschnitte: [
      { nr: 1, titel: "Ansagen, Töne & Tipps", zeilen: [
        [null, "💡 Tipp des Tages", "Beim Öffnen ab und zu ein kurzer Tipp. „👉 Ja, zeig mir wo“ führt direkt zur passenden Stelle."],
        [null, "🗣️ Sprachansagen", "Unter <b>„Auswählen“</b> kreuzt du an, was dein Handy ansagen soll: <b>wer online kommt</b>, neue Nachrichten, Anklopfen, Pinnwand, Helfen/Leihen/Börse, Mitfahrt, Standort mit Entfernung (Luftlinie) und Termine. <b>▶</b> spielt ein Beispiel, z. B. „Christina hat dir ein Post-it an die Pinnwand gehängt“. Am Anfang sind nur Nachrichten und Anklopfen an.", "neu"],
        [null, "Wer kommt, wer geht", "Neu ankreuzbar: <b>„🚪 Jemand verlässt die App“</b> („Klaus hat die Club-App verlassen“). Kommen mehrere gleichzeitig online, gibt es <b>eine</b> Ansage – bei mehr als 3: „5 Clubkameradinnen und Kameraden sind gerade online“.", "neu"],
        [null, "Wann spricht das Handy?", "Nur, solange die Köcheclub-App <b>offen</b> ist – nicht in deiner Ruhezeit und nicht für den Chat, den du gerade offen hast. Ist die App zu oder im Hintergrund, kommt der normale Push mit Ton (Android und iPhone erlauben Web-Apps im Hintergrund keine Sprache).", "neu"],
        [null, "🖍️ Tippfehler rot unterstreichen", "„Prüfen“ zeigt einen Testsatz mit zwei Fehlern und – passend zu deinem Handy – wie du die Rechtschreibprüfung einschaltest.", "neu"],
        [null, "🎤 Mikrofon im Chat", "Jedes Mal fragen, immer Sprachnachricht oder immer Diktieren.", "neu"],
        [null, "🔊 Neue Nachrichten vorlesen", "Liest neue Nachrichten im offenen Chat vor (wie der Lautsprecher im Chat)."]] },
      { nr: 2, titel: "Benachrichtigungen", zeilen: [
        [null, "Push und E-Mail je Bereich", "Für Termine, Nachrichten, Abstimmungen, Dienste, Geburtstage und Pinnwand einzeln wählen: aufs Handy, per Mail oder beides."],
        [null, "🌙 Nicht stören", "Eine Ruhezeit (z. B. 22–7 Uhr) ohne Push. Anrufe kommen trotzdem durch. Dein Status zeigt dann „Ruhezeit bis …“."]] },
      { nr: 3, titel: "Privatsphäre", zeilen: [
        [null, "Online und „zuletzt da“", "Ob andere sehen, dass du online bist bzw. wann du zuletzt da warst. Ausgeschaltet siehst du es bei anderen auch nicht – wie bei WhatsApp."],
        [null, "Anklopfen erlauben", "Ob andere bei dir anklopfen dürfen, wenn du online bist."],
        [null, "Geburtstag, Kontaktdaten", "Was andere von dir sehen dürfen – nichts wird ohne dein Einverständnis gezeigt."]] },
      { nr: 4, titel: "Darstellung", zeilen: [[null, "Lieblingsfarbe und Ansicht", "Farbe der App, Tag/Nacht und einfache oder erweiterte Ansicht."],
        [null, "🎨 Weitere Farbschemen", "Unter den 8 bekannten Farben klappt „Weitere Farbschemen“ 8 ruhige Töne auf: Toskana, Weinberg, Salbei, Lavendel, Ocker, Schokolade, Petrol, Rosé.", "neu"],
        ["s-farben-bunt", "✨ Ausgefallene Farbschemen", "6 Schemen mit Farbverlauf oben: Sonnenuntergang, Polarlicht, Kirschblüte, Tiefsee, Glut, Retro 70er. Antippen – die App färbt sich sofort um.", "neu"]] },
    ] },
  { titel: "9. Notbetrieb", unter: "Wenn der Server einmal ausfällt", bild: "notbetrieb",
    legende: [["Oranges Band", "die App läuft gerade im Notbetrieb"]],
    abschnitte: [{ nr: 1, titel: "Was im Notbetrieb geht", zeilen: [
      ["s-not-band", "Notbetrieb", "Fällt der Club-Server aus, schaltet die App <b>von selbst</b> auf einen Ersatz-Server um. Oben steht das orange Band mit der Uhrzeit des Stands."],
      [null, "Ansehen geht", "Termine, Mitglieder, SOS, Dienste, Pinnwand und Nachrichten – so, wie es zuletzt war."],
      [null, "Schreiben wird gespeichert", "Nachrichten in bestehenden Chats, Zu- und Absagen, Status und Zettel werden gespeichert (⏳ „wartet“) und <b>automatisch übertragen</b>, sobald alles wieder läuft."],
      [null, "Geht gerade nicht", "Fotos und Anlagen, neue Chats, Anrufe und Push. Die Notrufnummern (112 …) gehen <b>immer</b>."],
      [null, "Zurück", "Ist der Server wieder da, verschwindet das Band von selbst und alles Gespeicherte wird übertragen."]] }] },
  { titel: "10. Fotos & Alben", unter: "Eigene Fotoalben mit Namen – z. B. „Weihnachtsmarkt 2026“", bild: "fotos-auswahl",
    legende: [["Neues Album", "Fotos auswählen und ein Album anlegen"], ["Album", "antippen öffnet es – 👥 für alle, 🔒 nur für dich"], ["Auswahl", "„☑️ Auswählen“ / „Auswahl beenden“"], ["Ins Album", "die angehakten Fotos in ein Album legen"]],
    text: "So geht’s: im Fotoalbum auf <b>„☑️ Auswählen“</b> tippen, Fotos anhaken und <b>„📸 Ins Album“</b>. Ein Album ist nur eine Sammlung – die Fotos bleiben im Fotoalbum und brauchen keinen zusätzlichen Platz.",
    abschnitte: [{ nr: 4, titel: "In welches Album?", zeilen: [["s-album-wahl", "Album wählen oder neu anlegen", "Ein vorhandenes Album antippen oder <b>„＋ Neues Album …“</b>: Namen eingeben und festlegen, ob <b>alle Mitglieder</b> es sehen oder <b>nur du</b>.", "neu"]] }] },
  { titel: "11. Archiv & Chronik", unter: "Dein eigener Ordner, Fotoalben im Regal und die Clubchronik zum Blättern", bild: "archiv-regal",
    legende: [["Mein Ordner", "nur du siehst ihn – mit 🔓 kannst du anderen etwas auf Zeit freigeben"], ["Album", "deine Fotoalben stehen auch im Regal"], ["Clubchronik", "die Geschichte des Clubs"]],
    text: "Legt jemand anderes etwas in deinen Ordner (z. B. die Clubleitung eine Bestätigung), steht es dort erst <b>„zur Prüfung“</b> – du nimmst es an oder lehnst es ab.",
    weiter: [{ bild: "chronik-ordner", titel: "Die Clubchronik", legende: [["Blättern", "die Chronik wie ein Buch ansehen"], ["So füllen wir …", "kurze Anleitung, was hineingehört"], ["Beitrag einreichen", "Foto, Zeitungsartikel oder Dokument einreichen – die Clubleitung prüft und nimmt es auf"]],
      text: "Register wie Gründung, Presse, Rekorde & Höhepunkte, Feste & Jubiläen oder In Gedenken ordnen die Einträge." },
      { bild: "chronik-blaettern", titel: "Blättern", legende: [["Schließen", "zurück zur App"], ["Umblättern", "‹ › antippen oder wischen"], ["Register", "springt direkt zu einem Teil, unten zeigt der Balken, wo du bist"]],
      text: "Blättern geht in jedem Ordner im Archiv – Fotos, PDF und Dokumente erscheinen als Seiten." }] },
  { titel: "12. Helfen & Leihen", unter: "Hilfe suchen, helfen, „nach Absprache“ – über die Kachel „🤝 Helfen & Leihen“", bild: "hilfe-form",
    legende: [["Wobei?", "Art der Hilfe – bei „Sonstiges“ kurz eintragen"], ["Nach Absprache", "kein fester Tag – ihr macht den Termin miteinander aus"], ["Egal wie viele", "keine Grenze, jede Zusage zählt"]],
    text: "„🙋 Ich suche Hilfe“ öffnet dieses Formular. Bei <b>„📅 Bestimmter Tag“</b> wählst du Tag und Zeit, bei <b>„🤝 Nach Absprache“</b> bleibt der Aufruf 30 Tage offen. Alle Mitglieder bekommen eine Mitteilung und sehen den Aushang an der Pinnwand.",
    abschnitte: [{ nr: 4, titel: "Beschreibung", zeilen: [["s-hilfe-text", "Was genau?", "Großes Textfeld (bis 1000 Zeichen): was zu tun ist, was man mitbringen soll, wie man dich erreicht.", "neu"]] }],
    weiter: [{ bild: "hilfe-kurz", titel: "Einen Aufruf antippen", legende: [["Wer sucht", "Name"], ["Wobei", "was gebraucht wird"], ["Wann", "Tag oder „nach Absprache“"], ["Gesucht", "wie viele, wie viele schon dabei"], ["Beschreibung", "die Einzelheiten"], ["Ja, ich kann helfen", "zusagen"], ["Kann nicht", "absagen"], ["Mehr Details", "Nachricht an die Person, die sucht"]],
      text: "Du siehst nur die <b>Zusammenfassung</b> – keine Eingabefelder. „❓ Ich brauche noch mehr Details“ öffnet eine Nachricht mit vorbereitetem Anfang. Antworten kannst du später zurücknehmen.",
      abschnitte: [{ nr: 1, titel: "Dein eigener Aufruf", zeilen: [["s-hilfe-eigen", "So sehen ihn die Mitglieder", "Antippen zeigt dieselbe Zusammenfassung, darunter wer zugesagt hat und wie viele noch fehlen. <b>„✏️ Ändern“</b> öffnet das Formular (kein neuer Rundruf – nur wer zugesagt hat, erfährt von einer Tag- oder Ortsänderung). <b>„🔒 Aufruf schließen“</b> beendet ihn.", "neu"]] }] }] },
  { titel: "13. Bedienen, Anmelden & ohne Netz", unter: "Was überall in der App gleich funktioniert",
    abschnitte: [{ nr: 1, titel: "Zurück und Rückfragen", zeilen: [
      [null, "‹ und die Zurück-Taste", "‹ oben links und die Zurück-Taste des Handys gehen <b>einen Schritt zurück</b> – dorthin, wo du vorher warst. Ist ein Fenster offen, schließt Zurück <b>nur das Fenster</b>; was du angefangen hast, bleibt stehen.", "neu"],
      ["s-rueckfrage", "Rückfragen beim Löschen", "Der rote Knopf sagt, was passiert (<b>„🗑️ Löschen“</b>, „Absagen“ …). Vorausgewählt ist immer <b>„Abbrechen“</b> – so passiert nichts aus Versehen.", "neu"],
      ["s-verbindung-einfach", "Verbindung prüfen", "Lämpchen oben antippen: „✅ Verbindung in Ordnung“ oder „⚠️ Störung“. Mit „🧪 Test-Mitteilung an mich“ prüfst du, ob Mitteilungen ankommen.", "neu"]] },
      { nr: 2, titel: "Ohne Internet", zeilen: [
      [null, "App ohne Netz öffnen", "Die App zeigt deinen <b>letzten Stand</b> – oben steht deutlich „📴 Kein Netz – das ist dein Stand von …“. Kommt das Netz zurück, lädt sie von selbst neu.", "neu"],
      [null, "Nachrichten ohne Netz", "Werden vorgemerkt und automatisch gesendet (Teil 3).", "neu"]] },
      { nr: 3, titel: "Neues Gerät, neue Version", zeilen: [
      [null, "Einrichtungskarte", "Die Clubleitung kann dir eine Karte mit QR-Code ausdrucken: Kamera draufhalten, Link antippen – die App führt dich Schritt für Schritt. Kommt der Link aus WhatsApp oder Google Lens, sagt die App zuerst „In Safari/Chrome öffnen“.", "neu"],
      [null, "Updates und Startprobleme", "Neue Versionen kommen von selbst: Holst du die App zurück und tippst gerade nichts, aktualisiert sie sich kurz. Startet sie einmal nicht, erscheint nach 12 Sekunden Hilfe mit „🧹 Speicher der App leeren“ – deine Anmeldung bleibt erhalten.", "neu"]] }] },
];
