-- Nur lokale Testumgebung: Nachbau der Supabase-Strukturen (ohne Daten)
create extension if not exists pgcrypto;
do $$ begin if not exists (select 1 from pg_roles where rolname='anon') then create role anon nologin; create role authenticated nologin; create role service_role nologin bypassrls; end if; end $$;
create schema auth; create schema kc_private;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
grant usage on schema auth, kc_private, public to authenticated, anon, service_role;
grant execute on function auth.uid() to authenticated, anon;
create table public.kc_core_user_links(org_id text not null, user_id uuid not null, person_id text not null, core_role text not null default 'member', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.kc_core_app_access(org_id text not null, person_id text not null, app_id text not null, access_role text not null default 'user', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create function kc_private.kc_core_is_admin(p_org_id text) returns boolean language sql stable security definer set search_path to 'public','pg_temp' as $$
  select exists(select 1 from public.kc_core_user_links l where l.org_id=p_org_id and l.user_id=auth.uid() and l.active and l.core_role='admin') $$;
create function kc_private.kc_core_has_app_access(p_org_id text, p_app_id text, p_roles text[] default null) returns boolean language sql stable security definer set search_path to 'public','pg_catalog' as $$
  select exists (select 1 from public.kc_core_user_links l where l.org_id = p_org_id and l.user_id = auth.uid() and l.active
    and (l.core_role = 'admin' or exists (select 1 from public.kc_core_app_access a where a.org_id = l.org_id and a.person_id = l.person_id and a.app_id = p_app_id and a.active and (p_roles is null or a.access_role = any(p_roles))))) $$;
grant execute on all functions in schema kc_private to authenticated;
create table public.kc_core_people(person_id text not null, org_id text not null, display_name text not null, email text, phone text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), given_name text, family_name text, preferred_name text, birth_date date, street text, postal_code text, city text, country_code text not null default 'DE', primary key(org_id, person_id));
create table public.kc_core_club_memberships(org_id text not null, person_id text not null, member_number text, membership_type text not null default 'regular', membership_status text not null default 'active' check (membership_status = any(array['active','inactive','former','pending'])), joined_on date, left_on date, club_function text, board_function text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(org_id, person_id), check (left_on is null or joined_on is null or left_on >= joined_on), foreign key (org_id, person_id) references public.kc_core_people(org_id, person_id));
create table public.kc_club_aenderungen(id uuid not null default gen_random_uuid() primary key, person_id text not null, art text not null, alt jsonb, neu jsonb not null, gilt_ab date, bemerkung text, empfaenger text[] not null default '{}', an_alle boolean not null default false, status text not null default 'offen' check (status = any(array['offen','freigegeben','uebernommen','abgelehnt','rueckfrage','erledigt','zurueckgezogen'])), erledigt_von text, erledigt_am timestamptz, antwort text, versand jsonb, erstellt_am timestamptz not null default now(), org_id text not null default 'KC_WERNE', kenntnis jsonb not null default '[]', freigegeben_von text, freigegeben_am timestamptz, uebergabe jsonb, uebernommen_am timestamptz, uebernommen_von text, uebernahme_ergebnis jsonb, rueckfrage text, mitglied_informiert_am timestamptz);
create table public.kc_manager_memberships(org_id text not null, user_id uuid not null, role text not null, active boolean not null default true, created_at timestamptz not null default now(), person_id text, display_name text, email text, phone text, updated_at timestamptz not null default now());
create table public.kc_manager_state_sections(org_id text not null, section_key text not null, payload jsonb not null default '{}', version bigint not null default 1 check (version > 0), updated_at timestamptz not null default now(), updated_by uuid not null default auth.uid(), primary key (org_id, section_key), constraint kc_manager_state_sections_key_format check (section_key ~ '^[a-z][a-zA-Z0-9_]{1,79}$'));
alter table public.kc_manager_state_sections enable row level security;
grant select, insert, update on public.kc_manager_state_sections to authenticated;
create policy kc_manager_state_sections_select on public.kc_manager_state_sections for select to authenticated using (exists (select 1 from public.kc_manager_memberships m where m.org_id=kc_manager_state_sections.org_id and m.user_id=auth.uid()));
create policy kc_manager_state_sections_insert on public.kc_manager_state_sections for insert to authenticated with check (updated_by=auth.uid() and exists (select 1 from public.kc_manager_memberships m where m.org_id=kc_manager_state_sections.org_id and m.user_id=auth.uid() and m.role in ('operator','manager','admin')));
create policy kc_manager_state_sections_update on public.kc_manager_state_sections for update to authenticated using (exists (select 1 from public.kc_manager_memberships m where m.org_id=kc_manager_state_sections.org_id and m.user_id=auth.uid() and m.role in ('operator','manager','admin'))) with check (updated_by=auth.uid() and exists (select 1 from public.kc_manager_memberships m where m.org_id=kc_manager_state_sections.org_id and m.user_id=auth.uid() and m.role in ('operator','manager','admin')));
grant select, update on public.kc_core_people, public.kc_core_club_memberships to authenticated;
grant select on public.kc_core_user_links, public.kc_manager_memberships to authenticated;
